import Shared
import SwiftUI

/// "AI-generated" label for anything a model wrote (CLAUDE.md rule 10), with the engine that wrote it.
struct AIBadge: View {
    var engine: String?

    var body: some View {
        Label(engine.map { String(localized: "AI-generated · \($0)") } ?? String(localized: "AI-generated"), systemImage: "sparkles")
            .font(.caption2.weight(.medium))
            .padding(.horizontal, 6)
            .padding(.vertical, 2)
            .background(Color.purple.opacity(0.15), in: Capsule())
            .foregroundStyle(.purple)
            .accessibilityLabel(engine.map { String(localized: "AI-generated by \($0)") } ?? String(localized: "AI-generated"))
    }
}

/// Loads the speaking & listening practice pack, or shows an honest empty state when this build has none.
struct PracticeGate<Content: View>: View {
    @Environment(AppModel.self) private var app
    @ViewBuilder var content: (PracticeRepository) -> Content

    @State private var repo: PracticeRepository?
    @State private var loaded = false

    var body: some View {
        Group {
            if let repo {
                content(repo)
            } else if loaded {
                ContentUnavailableView(
                    "Practice pack not installed",
                    systemImage: "waveform.badge.exclamationmark",
                    description: Text("This build has no speaking & listening pack. Build it with `uv run packs/build_practice.py` in tools/ and rebuild the app.")
                )
            } else {
                ProgressView()
            }
        }
        .task {
            guard repo == nil else { return }
            repo = try? await app.graph.practice()
            loaded = true
        }
    }
}

/// Explains why AI features are off and links to Settings → AI. Hidden when a model is configured.
struct AiStatusBanner: View {
    @Environment(AppModel.self) private var app
    var scripted: String = "Without a model the partner follows the scenario's script and suggests sample answers."
    @State private var reason: String?

    var body: some View {
        Group {
            if let reason {
                VStack(alignment: .leading, spacing: 4) {
                    Label("Scripted mode", systemImage: "text.book.closed").font(.subheadline.weight(.semibold))
                    Text(reason).font(.caption)
                    Text(LocalizedStringKey(scripted)).font(.caption).foregroundStyle(.secondary)
                    NavigationLink("Set up AI", value: Route.aiSettings).font(.caption.weight(.semibold))
                }
                .frame(maxWidth: .infinity, alignment: .leading)
                .padding(10)
                .background(Color.orange.opacity(0.12), in: RoundedRectangle(cornerRadius: 10))
            }
        }
        .task { reason = try? await app.graph.ai.unavailableReason() }
    }
}

/// Tap to start recording, tap again to stop. Calls [onRecorded] with 16 kHz mono samples.
struct RecordButton: View {
    var recorder: Recorder
    var label: String = "Speak"
    var disabled: Bool = false
    let onRecorded: ([Float]) -> Void

    var body: some View {
        VStack(spacing: 4) {
            Button {
                if recorder.isRecording {
                    onRecorded(recorder.stop())
                } else {
                    Task { await recorder.start() }
                }
            } label: {
                // [label] is one of the literal keys callers pass ("Speak", "Record", "Answer", …), so it localizes.
                Label(LocalizedStringKey(recorder.isRecording ? "Stop" : label), systemImage: recorder.isRecording ? "stop.circle.fill" : "mic.circle.fill")
                    .frame(maxWidth: .infinity)
            }
            .buttonStyle(.borderedProminent)
            .tint(recorder.isRecording ? .red : .accentColor)
            .disabled(disabled && !recorder.isRecording)
            .accessibilityHint(recorder.isRecording ? Text("Stops recording and checks what you said.") : Text("Starts recording. Tap again to stop."))
            if recorder.isRecording {
                Text("Recording… tap Stop when you're done.").font(.caption).foregroundStyle(.secondary)
            }
            if let message = recorder.message {
                Text(message).font(.caption).foregroundStyle(.red)
            }
        }
    }
}

/// Mirrors of Kotlin models whose Swift names clash between packages (e.g. `Scenario`, `Dialogue`, `Speaker`),
/// so screens never need to spell those type names.
struct ScenarioSummary: Identifiable, Hashable {
    let id: String
    let titleEn: String
    let titleJa: String
    let jlpt: Int
    let ilr: String
    let category: String
    let aiGenerated: Bool
}

/// One JLPT level choice (5 = N5).
let jlptLevels = [5, 4, 3, 2, 1]

/// "m:ss" for a countdown.
func clockText(seconds: Int64) -> String {
    let s = max(0, seconds)
    return String(format: "%ld:%02ld", Int(s / 60), Int(s % 60))
}
