package app.tsumugi.android.features.reader

import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.verticalScroll
import androidx.compose.material3.Button
import androidx.compose.material3.Card
import androidx.compose.material3.HorizontalDivider
import androidx.compose.material3.LinearProgressIndicator
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.OutlinedButton
import androidx.compose.material3.Text
import androidx.compose.material3.TextButton
import androidx.compose.runtime.Composable
import androidx.compose.runtime.LaunchedEffect
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateMapOf
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.rememberCoroutineScope
import androidx.compose.runtime.setValue
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.drawBehind
import androidx.compose.ui.geometry.Offset
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.res.stringResource
import androidx.compose.ui.semantics.clearAndSetSemantics
import androidx.compose.ui.semantics.heading
import androidx.compose.ui.semantics.semantics
import androidx.compose.ui.unit.dp
import app.tsumugi.android.R
import app.tsumugi.android.features.practice.AiBadge
import app.tsumugi.android.features.practice.Notice
import app.tsumugi.android.features.practice.rememberGraph
import app.tsumugi.android.ui.ErrorState
import app.tsumugi.android.ui.JaText
import app.tsumugi.android.ui.japanese
import app.tsumugi.android.ui.readable
import app.tsumugi.reader.LearnerLevel
import app.tsumugi.reader.ReaderDocument
import app.tsumugi.reader.ReadingQuestionsResult
import app.tsumugi.reader.TokenPitch
import kotlinx.coroutines.CancellationException
import kotlinx.coroutines.Job
import kotlinx.coroutines.launch

/**
 * The pitch overlay for one token (G-07, D-114): its reading with a line high or low over each mora and a drop at
 * the downstep. Inflected or unlisted words show the reading dimmed, without a line ("unknown", never a guess).
 */
@Composable
fun PitchMarks(p: TokenPitch?) {
    if (p == null) {
        Spacer(Modifier.height(12.dp))
        return
    }
    val line = MaterialTheme.colorScheme.tertiary
    val known = p.heights.isNotEmpty()
    val morae = p.morae
    Text(
        morae.joinToString(""),
        Modifier.clearAndSetSemantics {}.drawBehind {
            if (!known || morae.isEmpty()) return@drawBehind
            val seg = size.width / morae.size
            val stroke = 1.5.dp.toPx()
            var prevY: Float? = null
            for (i in morae.indices) {
                val high = p.heights.getOrElse(i) { false }
                val y = if (high) stroke else size.height - stroke
                val x0 = i * seg
                prevY?.let { if (it != y) drawLine(line, Offset(x0, it), Offset(x0, y), stroke) }
                drawLine(line, Offset(x0, y), Offset(x0 + seg, y), stroke)
                prevY = y
            }
            // A drop after the last mora (odaka): the following particle goes low.
            if (p.heights.size > morae.size && p.heights[morae.size - 1] && !p.heights[morae.size]) {
                drawLine(line, Offset(size.width, stroke), Offset(size.width, size.height / 2), stroke)
            }
        },
        style = MaterialTheme.typography.labelSmall.japanese(),
        color = if (known) MaterialTheme.colorScheme.tertiary else Color.Gray.copy(alpha = 0.6f),
    )
}

/**
 * Comprehension questions for the document (G-07): generated by the model on request and cached per document.
 * Always labeled AI (rule 10). With no model, an honest "unavailable" and a way to set one up (rule 9).
 */
@Composable
fun QuestionsSheet(doc: ReaderDocument, level: LearnerLevel, onClose: () -> Unit, onOpenAiSettings: () -> Unit) {
    val graph = rememberGraph()
    val scope = rememberCoroutineScope()
    var result by remember(doc.id) { mutableStateOf<ReadingQuestionsResult?>(null) }
    var job by remember { mutableStateOf<Job?>(null) }
    var error by remember { mutableStateOf<String?>(null) }
    val picked = remember(doc.id) { mutableStateMapOf<Int, Int>() }
    val jlpt = "N${level.jlpt ?: 4}"
    LaunchedEffect(doc.id) {
        graph.reader.questions.cached(doc.id)?.let { result = ReadingQuestionsResult.Ready(it) }
    }
    fun generate(regenerate: Boolean) {
        error = null
        picked.clear()
        job = scope.launch {
            try {
                result = graph.reader.questions.questions(doc, jlpt, 3, regenerate)
            } catch (e: CancellationException) {
                throw e
            } catch (e: Exception) {
                error = e.readable()
            } finally {
                job = null
            }
        }
    }
    Card(Modifier.fillMaxSize().padding(8.dp)) {
        Column(Modifier.fillMaxSize().verticalScroll(rememberScrollState()).padding(16.dp), verticalArrangement = Arrangement.spacedBy(8.dp)) {
            Row(horizontalArrangement = Arrangement.spacedBy(8.dp)) {
                Text(stringResource(R.string.reader_questions), Modifier.weight(1f).semantics { heading() }, style = MaterialTheme.typography.titleLarge)
                TextButton(onClick = { job?.cancel(); onClose() }) { Text(stringResource(R.string.action_close)) }
            }
            if (job != null) {
                Text(stringResource(R.string.reader_questions_working))
                LinearProgressIndicator(Modifier.fillMaxWidth())
                TextButton(onClick = { job?.cancel() }) { Text(stringResource(R.string.action_cancel)) }
            }
            error?.let { ErrorState(stringResource(R.string.error_loading, it), onRetry = { generate(false) }) }
            when (val r = result) {
                null -> if (job == null) {
                    Text(stringResource(R.string.reader_questions_intro), style = MaterialTheme.typography.bodyMedium)
                    Button(onClick = { generate(false) }) { Text(stringResource(R.string.reader_questions_generate)) }
                }
                is ReadingQuestionsResult.Unavailable -> {
                    Notice(stringResource(R.string.reader_questions_unavailable, r.reason), actionLabel = stringResource(R.string.ai_open_settings), onAction = onOpenAiSettings)
                }
                is ReadingQuestionsResult.Ready -> {
                    AiBadge(r.value.engine)
                    r.value.questions.forEachIndexed { qi, q ->
                        HorizontalDivider()
                        JaText("${qi + 1}. ${q.question}", style = MaterialTheme.typography.titleMedium)
                        val choice = picked[qi]
                        q.choices.forEachIndexed { ci, c ->
                            val color = when {
                                choice == null -> MaterialTheme.colorScheme.onSurface
                                ci == q.answer -> Color(0xFF2E7D32)
                                ci == choice -> Color(0xFFC62828)
                                else -> MaterialTheme.colorScheme.onSurfaceVariant
                            }
                            OutlinedButton(onClick = { if (choice == null) picked[qi] = ci }, modifier = Modifier.fillMaxWidth()) {
                                Text(c, color = color, style = MaterialTheme.typography.bodyLarge.japanese())
                            }
                        }
                        if (choice != null) {
                            Text(stringResource(if (choice == q.answer) R.string.review_correct else R.string.review_not_quite), style = MaterialTheme.typography.titleSmall)
                            if (q.explanation.isNotBlank()) Text(q.explanation, style = MaterialTheme.typography.bodyMedium.japanese())
                        }
                    }
                    TextButton(onClick = { generate(true) }, enabled = job == null) { Text(stringResource(R.string.reader_questions_again)) }
                }
            }
        }
    }
}
