"""Generate shared/.../coverage/IlrBandData.kt from tools/items/ilr_bands.json, so the app's difficulty score
(BRIEF_V2 §6.4, docs/CONTENT_PACKS.md "Difficulty score") and the DLPT item gates share one source of truth.

    uv run python packs/gen_ilr_bands.py            # rewrite the Kotlin file
    uv run python packs/gen_ilr_bands.py --check    # exit 1 when the Kotlin file is stale (CI / pre-commit)
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
BANDS = REPO / "tools" / "items" / "ilr_bands.json"
OUT = REPO / "shared/src/commonMain/kotlin/app/tsumugi/coverage/IlrBandData.kt"


def kstr(s: str) -> str:
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"').replace("$", "\\$") + '"'


def render() -> str:
    data = json.loads(BANDS.read_text(encoding="utf-8"))
    lines = [
        "// GENERATED by tools/packs/gen_ilr_bands.py from tools/items/ilr_bands.json. Do not edit by hand:",
        "// edit the JSON and re-run the script (`--check` verifies this file is current).",
        "package app.tsumugi.coverage",
        "",
        "/** One ILR level's passage band (tools/items/ilr_bands.json \"levels\"). Ranges are inclusive. */",
        "data class IlrBand(",
        "    val level: String,",
        "    val minChars: Int,",
        "    val maxChars: Int,",
        "    val kanjiDensityMin: Double,",
        "    val kanjiDensityMax: Double,",
        "    val abstractRatioMin: Double,",
        "    val abstractRatioMax: Double,",
        ")",
        "",
        "/** The ILR passage bands and the abstract-vocabulary lexicon, in level order 0+ … 3. */",
        "object IlrBandData {",
        "    val bands: List<IlrBand> = listOf(",
    ]
    for level, b in data["levels"].items():
        kd, ar = b["kanjiDensity"], b["abstractRatio"]
        lines.append(
            f"        IlrBand({kstr(level)}, {b['minChars']}, {b['maxChars']}, {float(kd[0])}, {float(kd[1])}, "
            f"{float(ar[0])}, {float(ar[1])}),"
        )
    lines += ["    )", "", "    val abstractLexicon: List<String> = listOf("]
    words = data["abstractLexicon"]
    for i in range(0, len(words), 10):
        lines.append("        " + ", ".join(kstr(w) for w in words[i : i + 10]) + ",")
    lines += ["    )", "}", ""]
    return "\n".join(lines)


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true", help="fail when the generated file is out of date")
    args = ap.parse_args()
    text = render()
    if args.check:
        current = OUT.read_text(encoding="utf-8") if OUT.exists() else ""
        if current != text:
            print(f"{OUT.relative_to(REPO)} is stale; run packs/gen_ilr_bands.py", file=sys.stderr)
            sys.exit(1)
        return
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(text, encoding="utf-8", newline="\n")
    print(f"wrote {OUT.relative_to(REPO)}")


if __name__ == "__main__":
    main()
