"""Render the iOS app icon from the Android launcher vector (the spool-of-thread mark).

    cd tools
    uv run --group assets python assets/render_icon.py          # writes SVG + three PNGs
    uv run --group assets python assets/render_icon.py --check  # only verify the Android vector is unchanged

Source of truth: androidApp/src/main/res/drawable/ic_launcher_{background,foreground}.xml. The geometry below is
a port of those files (same pathData strings); the script refuses to run if the Android files drift from it, so
the two platforms keep one mark. It writes:

- tools/assets/icon.svg: the port as plain SVG (viewBox = the 72dp area an adaptive icon shows, 18..90).
- AppIcon.appiconset/AppIcon.png: 1024x1024, opaque RGB (App Store rejects alpha in the marketing icon).
- AppIcon-dark.png: iOS 18 dark appearance. Transparent background so the system's dark backdrop shows through.
- AppIcon-tinted.png: iOS 18 tinted appearance. Grayscale mark on transparent; the system applies the tint.

Rendering uses Pillow primitives (rectangles, rounded rectangles, thick polylines, a flattened cubic Bezier) at
4x and downsamples with Lanczos for anti-aliasing. No cairo, so it runs on Windows ARM64 as well as macOS/Linux.
"""

from __future__ import annotations

import argparse
import re
import sys
from itertools import pairwise
from pathlib import Path

from PIL import Image, ImageDraw

REPO = Path(__file__).resolve().parents[2]
ANDROID_RES = REPO / "androidApp/src/main/res/drawable"
APPICON = REPO / "iosApp/Tsumugi/Resources/Assets.xcassets/AppIcon.appiconset"
SVG_OUT = Path(__file__).resolve().parent / "icon.svg"

SIZE = 1024
SUPERSAMPLE = 4
# Adaptive icons draw on a 108dp canvas and show the inner 72dp (18..90); that square becomes the iOS icon.
VIEW_MIN, VIEW_SIZE = 18.0, 72.0

BACKGROUND = "#3F4A8A"  # indigo
THREAD = "#C8553D"
CREAM = "#F3E9D7"
LOOSE_END = "#F0A08A"
WINDING_ALPHA = 0.55

# pathData strings exactly as in the Android vectors (checked by verify_android_source()).
PATH_BACKGROUND = "M0,0h108v108h-108z"
PATH_THREAD = "M39,36h30v36h-30z"
PATH_WINDINGS = "M39,43.5L69,42.5M39,49.5L69,48.5M39,55.5L69,54.5M39,61.5L69,60.5M39,67.5L69,66.5"
PATH_FLANGE_TOP = "M37,30H71A3,3 0,0 1,74 33V34A3,3 0,0 1,71 37H37A3,3 0,0 1,34 34V33A3,3 0,0 1,37 30Z"
PATH_FLANGE_BOTTOM = "M37,71H71A3,3 0,0 1,74 74V75A3,3 0,0 1,71 78H37A3,3 0,0 1,34 75V74A3,3 0,0 1,37 71Z"
PATH_LOOSE_END = "M69,58C77,59 72,69 79,73"

# The same shapes as primitives for Pillow.
THREAD_RECT = (39, 36, 69, 72)
WINDINGS = [((39, 43.5), (69, 42.5)), ((39, 49.5), (69, 48.5)), ((39, 55.5), (69, 54.5)),
            ((39, 61.5), (69, 60.5)), ((39, 67.5), (69, 66.5))]
WINDING_WIDTH = 1.4
FLANGES = [(34, 30, 74, 37), (34, 71, 74, 78)]
FLANGE_RADIUS = 3
LOOSE_END_BEZIER = ((69, 58), (77, 59), (72, 69), (79, 73))
LOOSE_END_WIDTH = 2.6


def verify_android_source() -> None:
    expected = {
        "ic_launcher_background.xml": [PATH_BACKGROUND],
        "ic_launcher_foreground.xml": [PATH_THREAD, PATH_WINDINGS, PATH_FLANGE_TOP, PATH_FLANGE_BOTTOM,
                                       PATH_LOOSE_END],
    }
    colors = {"ic_launcher_background.xml": [BACKGROUND],
              "ic_launcher_foreground.xml": [THREAD, CREAM, LOOSE_END]}
    for name, paths in expected.items():
        text = (ANDROID_RES / name).read_text(encoding="utf-8")
        found = re.findall(r'android:pathData="([^"]+)"', text)
        if found != paths:
            sys.exit(f"{name} changed (pathData {found}); update tools/assets/render_icon.py to match")
        for color in colors[name]:
            if color.upper() not in text.upper():
                sys.exit(f"{name} no longer uses {color}; update tools/assets/render_icon.py to match")


def svg(background: bool = True) -> str:
    bg = f'  <path fill="{BACKGROUND}" d="{PATH_BACKGROUND}"/>\n' if background else ""
    return (
        f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="{VIEW_MIN:g} {VIEW_MIN:g} {VIEW_SIZE:g} {VIEW_SIZE:g}" '
        f'width="{SIZE}" height="{SIZE}">\n'
        "  <!-- Tsumugi: a spool of thread with a loose end. Generated by tools/assets/render_icon.py from "
        "androidApp/src/main/res/drawable/ic_launcher_*.xml. -->\n"
        f"{bg}"
        f'  <path fill="{THREAD}" d="{PATH_THREAD}"/>\n'
        f'  <path fill="none" stroke="{CREAM}" stroke-opacity="{WINDING_ALPHA}" stroke-width="{WINDING_WIDTH}" '
        f'stroke-linecap="round" d="{PATH_WINDINGS}"/>\n'
        f'  <path fill="{CREAM}" d="{PATH_FLANGE_TOP}"/>\n'
        f'  <path fill="{CREAM}" d="{PATH_FLANGE_BOTTOM}"/>\n'
        f'  <path fill="none" stroke="{LOOSE_END}" stroke-width="{LOOSE_END_WIDTH}" stroke-linecap="round" '
        f'd="{PATH_LOOSE_END}"/>\n'
        "</svg>\n"
    )


# --- Pillow rendering -----------------------------------------------------------------------------------------

def _scale() -> float:
    return SIZE * SUPERSAMPLE / VIEW_SIZE


def _pt(x: float, y: float) -> tuple[float, float]:
    s = _scale()
    return ((x - VIEW_MIN) * s, (y - VIEW_MIN) * s)


def _rgba(hex_color: str, alpha: float = 1.0) -> tuple[int, int, int, int]:
    h = hex_color.lstrip("#")
    return (int(h[0:2], 16), int(h[2:4], 16), int(h[4:6], 16), round(alpha * 255))


def _stroke(draw: ImageDraw.ImageDraw, points: list[tuple[float, float]], width: float, fill) -> None:
    """Polyline with round joins and round caps (Android strokeLineCap="round"), drawn by stamping disks along
    the path. Pillow's wide `line` leaves hairline gaps between short segments of a curve."""
    r = width * _scale() / 2
    step = max(1.0, r / 8)
    for (x0, y0), (x1, y1) in pairwise(points):
        n = max(1, int(((x1 - x0) ** 2 + (y1 - y0) ** 2) ** 0.5 / step))
        for i in range(n + 1):
            x, y = x0 + (x1 - x0) * i / n, y0 + (y1 - y0) * i / n
            draw.ellipse((x - r, y - r, x + r, y + r), fill=fill)


def _bezier(p0, p1, p2, p3, steps: int = 96) -> list[tuple[float, float]]:
    out = []
    for i in range(steps + 1):
        t = i / steps
        u = 1 - t
        x = u**3 * p0[0] + 3 * u * u * t * p1[0] + 3 * u * t * t * p2[0] + t**3 * p3[0]
        y = u**3 * p0[1] + 3 * u * u * t * p1[1] + 3 * u * t * t * p2[1] + t**3 * p3[1]
        out.append(_pt(x, y))
    return out


def render_mark() -> Image.Image:
    """The foreground layer on a transparent canvas, supersampled."""
    big = SIZE * SUPERSAMPLE
    s = _scale()
    img = Image.new("RGBA", (big, big), (0, 0, 0, 0))
    draw = ImageDraw.Draw(img)
    draw.rectangle((*_pt(*THREAD_RECT[:2]), *_pt(*THREAD_RECT[2:])), fill=_rgba(THREAD))

    windings = Image.new("RGBA", img.size, (0, 0, 0, 0))
    wd = ImageDraw.Draw(windings)
    for a, b in WINDINGS:
        _stroke(wd, [_pt(*a), _pt(*b)], WINDING_WIDTH, _rgba(CREAM))
    # Apply strokeAlpha to the whole layer so overlapping caps don't double up.
    windings.putalpha(windings.getchannel("A").point(lambda v: round(v * WINDING_ALPHA)))
    img = Image.alpha_composite(img, windings)
    draw = ImageDraw.Draw(img)

    for x0, y0, x1, y1 in FLANGES:
        draw.rounded_rectangle((*_pt(x0, y0), *_pt(x1, y1)), radius=FLANGE_RADIUS * s, fill=_rgba(CREAM))
    _stroke(draw, _bezier(*LOOSE_END_BEZIER), LOOSE_END_WIDTH, _rgba(LOOSE_END))
    return img


def _downsample(img: Image.Image) -> Image.Image:
    return img.resize((SIZE, SIZE), Image.Resampling.LANCZOS)


def render_light(mark: Image.Image) -> Image.Image:
    bg = Image.new("RGBA", mark.size, _rgba(BACKGROUND))
    return _downsample(Image.alpha_composite(bg, mark)).convert("RGB")


def render_dark(mark: Image.Image) -> Image.Image:
    return _downsample(mark)


def render_tinted(mark: Image.Image) -> Image.Image:
    """Grayscale luminance of the mark, stretched so the flanges are near white; alpha kept."""
    small = _downsample(mark)
    gray = small.convert("L").point(lambda v: min(255, round(v * 255 / 235)))
    return Image.merge("LA", (gray, small.getchannel("A")))


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true", help="only verify the Android vector matches this port")
    args = ap.parse_args()
    verify_android_source()
    if args.check:
        print("Android launcher vector matches render_icon.py")
        return
    SVG_OUT.write_text(svg(), encoding="utf-8")
    mark = render_mark()
    render_light(mark).save(APPICON / "AppIcon.png", optimize=True)
    render_dark(mark).save(APPICON / "AppIcon-dark.png", optimize=True)
    render_tinted(mark).save(APPICON / "AppIcon-tinted.png", optimize=True)
    for name in ("AppIcon.png", "AppIcon-dark.png", "AppIcon-tinted.png"):
        with Image.open(APPICON / name) as im:
            print(f"{name}: {im.size[0]}x{im.size[1]} {im.mode}")


if __name__ == "__main__":
    main()
