"""The seed term catalog for tools/terms/seed_terms.csv (BRIEF_PHASE8 §B.2.2, C-01a, D-028).

Each row: (term_en as shown, domain, priority, lookup names, original definition or None, note).
- Lookup names are tried in each doctrinal source in the D-028 order; the first hit supplies `definition_en`
  verbatim with its page. The display term keeps the acronym the source gives ("Also called ...").
- An original one-sentence definition is used only when no public US source defines the term; those rows get
  `definition_source = original` (the gate allows at most 10%).
- Priority 1 = the §B.2.2 starter list (must ship); 2 = should; 3 = nice.
Domains: cuas, base-defense, airspace, ew, roe, c2, logistics, medical, hadr, brevity.
"""
from __future__ import annotations

O = None  # no original definition: must resolve from doctrine

# fmt: off
CATALOG: list[tuple[str, str, int, list[str], str | None, str]] = [
    # ---------------------------------------------------------------- counter-UAS (starter list)
    ("unmanned aircraft system", "cuas", 1, ["unmanned aircraft system"], O, ""),
    ("unmanned aircraft", "cuas", 1, ["unmanned aircraft"], O, ""),
    ("small unmanned aircraft system (sUAS)", "cuas", 1, [],
     "An unmanned aircraft system whose aircraft weighs less than 55 pounds, together with its ground control station and data links.",
     "Weight threshold as in US civil aviation rules (14 CFR part 107); in doctrine sUAS usually means Groups 1–2."),
    ("UAS group (Groups 1–5)", "cuas", 1, [],
     "One of five size classes the US military uses for unmanned aircraft, from Group 1 (under 20 pounds, low and slow) to Group 5 (over 1,320 pounds, flying above 18,000 feet).",
     "Groups by maximum weight, operating altitude and speed; table in ATP 3-01.81 ch. 1."),
    ("first-person-view (FPV) drone", "cuas", 1, [],
     "A small drone flown by an operator who watches a live video feed from its onboard camera, often through goggles, and often used as a guided explosive weapon.", ""),
    ("loitering munition (one-way attack UAS)", "cuas", 1, [],
     "An unmanned aircraft that carries a warhead, waits over an area until it finds a target, and then dives into it, destroying itself in the attack.", ""),
    ("swarm", "cuas", 1, [],
     "A group of unmanned aircraft that operate together under coordinated or automated control to overwhelm defenses or complete a shared task.", ""),
    ("fixed-wing aircraft", "cuas", 1, ["fixed-wing aircraft"],
     "An aircraft that gets lift from wings that do not move, so it must keep moving forward to stay in the air.", ""),
    ("rotary-wing aircraft", "cuas", 1, ["rotary-wing aircraft"],
     "An aircraft that gets lift from spinning rotor blades, so it can take off vertically and hover.", ""),
    ("multirotor drone", "cuas", 1, [],
     "A drone lifted by several horizontal propellers (commonly four, six or eight) that lets it hover and change direction quickly.", ""),
    ("counter-unmanned aircraft system (C-UAS)", "cuas", 1, ["counter-unmanned aircraft system", "counter-small unmanned aircraft system"],
     "The equipment, people and procedures used to detect, track, identify and defeat hostile or unauthorized unmanned aircraft.", ""),
    ("layered defense", "cuas", 1, ["layered defense", "defense in depth"],
     "A defense that places several sensors and weapons at different ranges so that a threat that gets past one layer can still be stopped by the next.", ""),
    ("detection", "cuas", 1, [], "In counter-UAS, the first step: sensing that an aircraft or drone is present, by radar, radio-frequency, optical or acoustic sensors.", "The DoD Dictionary entry is the CBRN sense."),
    ("tracking", "cuas", 1, ["tracking"], O, ""),
    ("identification", "cuas", 1, ["identification"], O, ""),
    ("defeat", "cuas", 1, ["defeat"],
     "In counter-UAS, the step that stops an unmanned aircraft from completing its mission, by destroying it, disabling it or taking control of it.", ""),
    ("kinetic defeat", "cuas", 1, [],
     "Stopping an unmanned aircraft by physically hitting it, for example with gunfire, a missile, an interceptor drone or a net.",
     "Also 'hard kill'."),
    ("non-kinetic defeat", "cuas", 1, [],
     "Stopping an unmanned aircraft without physically hitting it, for example by jamming its control link or its satellite navigation.",
     "Also 'soft kill'."),
    ("radio-frequency (RF) detection", "cuas", 1, [],
     "Finding a drone by picking up the radio signals passing between it and its controller, which can also point to where the operator is.", ""),
    ("radar", "cuas", 1, ["radar"],
     "A sensor that sends out radio waves and measures their echoes to find the position, speed and direction of objects such as aircraft.", ""),
    ("electro-optical/infrared (EO/IR) sensor", "cuas", 1, [],
     "A camera system that uses visible light and heat images to see, follow and identify a target by day or night.", ""),
    ("acoustic sensor", "cuas", 1, [],
     "A sensor that detects a drone by listening for the sound of its motors and propellers.", ""),
    ("active defense", "cuas", 1, ["active defense"], O, ""),
    ("passive defense", "cuas", 1, ["passive defense"], O, ""),
    ("electromagnetic jamming", "cuas", 1, ["electromagnetic jamming"], O, "Usually just 'jamming'."),
    ("spoofing", "cuas", 1, [],
     "Sending false signals, such as fake satellite navigation data, so that a drone or receiver believes it is somewhere it is not.", ""),
    ("navigation warfare", "cuas", 1, ["navigation warfare"],
     "Actions to deny an adversary the use of satellite navigation (GNSS/GPS) while protecting its use by friendly forces.", "Covers GNSS/GPS denial."),
    ("directed energy", "cuas", 1, ["directed energy"], O, ""),
    ("directed-energy weapon", "cuas", 1, ["directed-energy weapon"],
     "A weapon, such as a high-energy laser or a high-power microwave system, that damages or disables its target with concentrated energy instead of a projectile.",
     "High-energy laser (HEL); high-power microwave (HPM)."),
    ("interceptor drone", "cuas", 1, [],
     "A drone launched to chase and destroy or capture a hostile drone in the air.", ""),
    ("net capture", "cuas", 1, [],
     "Defeating a small drone by catching it in a net fired from the ground or carried by another drone.", ""),
    ("command and control (C2) link", "cuas", 1, [],
     "The radio connection over which an operator sends commands to an unmanned aircraft and receives its status.", ""),
    ("data link", "cuas", 1, ["data link", "datalink"], "A radio connection that passes data, such as video, position and commands, between an aircraft and the ground or other units.", ""),
    ("frequency band", "cuas", 1, [],
     "A range of radio frequencies; many small drones use the 2.4 GHz and 5.8 GHz bands for control and video.", ""),
    ("remote identification (Remote ID)", "cuas", 1, [],
     "A drone's broadcast of its identity, location and the location of its control station, which receivers on the ground can read.", ""),
    ("drone operator location", "cuas", 1, [],
     "The place from which a person is controlling a drone; finding it lets security forces stop the threat at its source.", ""),
    ("launch point", "cuas", 1, [],
     "The place from which an unmanned aircraft takes off.", ""),
    ("recovery point", "cuas", 1, [],
     "The place where an unmanned aircraft is planned to land or be collected after its flight.", ""),
    ("flight profile", "cuas", 1, ["flight profile"],
     "The planned or observed path of an aircraft in altitude, speed and direction over time.", ""),
    ("loiter", "cuas", 1, [],
     "To stay over or near an area for a period of time, for example to watch it or to wait for a target.", ""),
    ("ingress", "cuas", 1, ["ingress"],
     "The movement of an aircraft into an area toward its target or objective.", "Opposite: egress."),
    ("egress", "cuas", 1, ["egress"],
     "The movement of an aircraft out of a target area after completing its task.", ""),
    ("mass raid", "cuas", 1, [],
     "An attack by many aircraft, drones or missiles arriving at the same time to overload the defenses.", "Related: saturation."),
    ("saturation", "cuas", 1, [],
     "The point at which more threats arrive than the defense can detect, track or engage at once.", ""),
    ("collateral damage", "cuas", 1, ["collateral damage"], O, "Collateral damage estimate (CDE) is the process that predicts it."),
    ("weapon engagement zone", "cuas", 1, ["weapon engagement zone"], O, "Engagement zone: the general idea; see also missile and fighter engagement zones."),
    ("weapons control status", "cuas", 1, ["weapons control status"], O, "Weapons free / weapons tight / weapons hold."),
    ("weapons free", "roe", 1, ["weapons free"], O, ""),
    ("weapons tight", "roe", 1, ["weapons tight"], O, ""),
    ("weapons hold", "roe", 1, ["weapons hold"], O, ""),
    ("rules of engagement", "roe", 1, ["rules of engagement"], O, ""),
    ("hostile act", "roe", 1, ["hostile act"], O, ""),
    ("hostile intent", "roe", 1, ["hostile intent"], O, ""),
    ("positive identification", "roe", 1, ["positive identification"], O, ""),
    ("track number", "airspace", 1, ["track number"],
     "The number assigned to an air track so that everyone in the air defense system refers to the same object.", ""),
    ("track", "airspace", 1, ["track"], O, ""),
    ("common operational picture", "c2", 1, ["common operational picture"],
     "A single shared display of relevant information, such as the air picture, that several commands use to understand the situation.",
     "Air picture = the part showing aircraft tracks."),
    ("airspace coordinating measures", "airspace", 1, ["airspace coordinating measures", "airspace control measures"], O, ""),
    ("restricted operations zone", "airspace", 1, ["restricted operations zone"],
     "Airspace reserved for a specific activity, such as drone operations, in which other aircraft are restricted.", ""),
    ("no-drone zone", "airspace", 1, [],
     "An area where flying drones is prohibited, usually around bases, airports and sensitive sites.", ""),
    ("temporary flight restriction", "airspace", 1, ["temporary flight restriction"],
     "A temporary ban or limit on flights in a defined area, announced to pilots, for example over an emergency or a VIP visit.", ""),
    ("air defense warning condition", "airspace", 1, ["air defense warning condition"], O, "Red / yellow / white."),
    # ---------------------------------------------------------------- base defense (starter list)
    ("base defense operations center", "base-defense", 1, ["base defense operations center"], O, ""),
    ("base defense", "base-defense", 1, ["base defense"], O, ""),
    ("force protection", "base-defense", 1, ["force protection"], O, ""),
    ("force protection condition", "base-defense", 1, ["force protection condition"], O, ""),
    ("entry control point", "base-defense", 1, ["entry control point"],
     "A guarded gate where people and vehicles are checked before they are allowed onto an installation.", ""),
    ("vehicle search area", "base-defense", 1, [],
     "An area at or near an entry point, set apart from people and buildings, where vehicles are stopped and searched.", ""),
    ("perimeter", "base-defense", 1, ["perimeter"],
     "The outer boundary of a base or position, usually marked by fences or barriers and watched by guards.", ""),
    ("sector", "base-defense", 1, ["sector"],
     "An area of responsibility assigned to a unit; a sector sketch shows its boundaries, positions and fields of fire.", ""),
    ("observation post", "base-defense", 1, ["observation post"],
     "A position from which soldiers watch an area and report what they see.", "Listening post: the same at night or by sound."),
    ("listening post", "base-defense", 1, ["listening post"],
     "A position placed in front of the defense, usually at night, to give early warning by listening for enemy movement.", ""),
    ("quick reaction force", "base-defense", 1, ["quick reaction force"],
     "A unit kept ready to move at short notice to respond to an incident or reinforce a threatened area.", ""),
    ("security forces", "base-defense", 1, ["security forces"], O, ""),
    ("defender", "base-defense", 1, [],
     "A member of a security force on duty protecting a base, its people and its resources.", "US Air Force Security Forces call their members Defenders."),
    ("patrol", "base-defense", 1, ["patrol"],
     "A detachment sent out to gather information or provide security, on foot (dismounted) or in vehicles (mounted).", ""),
    ("random antiterrorism measure", "base-defense", 1, ["random antiterrorism measure"],
     "A security measure applied at irregular times and places so that an attacker cannot predict the defense.", ""),
    ("standoff distance", "base-defense", 1, ["standoff distance"],
     "The distance kept between a possible bomb, such as a vehicle, and the people or buildings it could harm.", ""),
    ("barrier", "base-defense", 1, ["barrier"], O, "Barrier plan: where barriers go and who closes them."),
    ("blast mitigation", "base-defense", 1, [],
     "Measures, such as barriers, film on windows and distance, that reduce the harm an explosion can do.", ""),
    ("alarm condition", "base-defense", 1, [],
     "A posted state that tells everyone on a base whether an attack is unlikely, expected or under way, and what protective action to take.", ""),
    ("post-attack reconnaissance", "base-defense", 1, [],
     "The check of a base after an attack to find damage, casualties and unexploded ordnance.", ""),
    ("unexploded explosive ordnance", "base-defense", 1, ["unexploded explosive ordnance"], O, "Commonly UXO."),
    ("shelter in place", "base-defense", 1, [],
     "To stay indoors or in the nearest protected place until told it is safe to move.", ""),
    ("bunker", "base-defense", 1, [],
     "A reinforced shelter, often of concrete or sandbags, that protects people from blast and fragments.", ""),
    ("cover and concealment", "base-defense", 1, [],
     "Cover protects from fire; concealment only hides from view.", ""),
    ("accountability", "base-defense", 1, [],
     "Knowing where every person is and whether they are safe, especially after an attack or alarm.", ""),
    ("lockdown", "base-defense", 1, [],
     "An order that stops all movement on an installation or in a building until the threat has passed.", ""),
    ("all clear", "base-defense", 1, [],
     "The announcement that a threat has ended and normal activity may resume.", ""),
    ("incident commander", "base-defense", 1, ["incident commander"],
     "The person in charge of all response activity at the scene of an incident.", ""),
    ("emergency operations center", "base-defense", 1, ["emergency operations center"],
     "The facility from which leaders coordinate the response to an emergency.", ""),
    ("mass notification", "base-defense", 1, [],
     "A system that warns everyone on an installation at once, through sirens, loudspeakers, phones and computers.", ""),
    ("indirect fire", "base-defense", 1, ["indirect fire"], "Fire, such as mortar, rocket or artillery rounds, aimed at a target the firer cannot see, usually along a high curved path.", ""),
    ("counter-rocket, artillery, and mortar (C-RAM)", "base-defense", 1, ["counter-rocket, artillery, and mortar"],
     "A system that detects incoming rockets, artillery and mortar rounds, warns the base and can shoot them down.", ""),
    ("insider threat", "base-defense", 1, ["insider threat"], "The risk that a person with authorized access, such as an employee or contractor, uses that access to cause harm.", ""),
    ("host nation", "base-defense", 1, ["host nation"], O, ""),
    ("foreign security forces", "base-defense", 1, ["foreign security forces"], O, "Here: host-nation security forces."),
    ("status-of-forces agreement", "base-defense", 1, ["status-of-forces agreement"], O, ""),
    ("jurisdiction", "base-defense", 1, ["jurisdiction"],
     "The legal authority to investigate, arrest and try people for offenses in a given place.", ""),
    ("local national", "base-defense", 1, ["local national"],
     "A citizen of the host country, for example one working on or near a base.", ""),
    ("escort", "base-defense", 1, ["escort"],
     "A person assigned to accompany a visitor or contractor who may not move on the base alone.", ""),
    ("access roster", "base-defense", 1, [],
     "The list of people authorized to enter a facility or area, checked against their badges.", ""),
    ("shift handover", "base-defense", 1, [],
     "Passing the current situation, open issues and equipment from one duty shift to the next.", ""),
    ("blotter", "base-defense", 1, [],
     "The chronological log in which a security or police desk records incidents and actions.", ""),
    ("chain of custody", "base-defense", 1, ["chain of custody"], "The written record of everyone who has held a piece of evidence, from collection onward, so it can be trusted.", ""),
    # ---------------------------------------------------------------- airspace and C2 (starter list)
    ("airspace control", "airspace", 1, ["airspace control"], O, ""),
    ("air tasking order", "airspace", 1, ["air tasking order"], O, ""),
    ("air defense artillery", "airspace", 1, ["air defense artillery"], O, ""),
    ("identification, friend or foe", "airspace", 1, ["identification, friend or foe"], O, "Mode 5 = the current secure military IFF mode."),
    ("squawk", "airspace", 1, [],
     "The code an aircraft's transponder sends; 'squawk' is also the order to set that code.", ""),
    ("altitude block", "airspace", 1, [],
     "A band of altitudes, between a lower and an upper limit, assigned to one aircraft or activity.", ""),
    ("deconfliction", "airspace", 1, ["deconfliction"],
     "Coordinating times, places and altitudes so that friendly aircraft, drones and fires do not interfere with or endanger each other.", ""),
    ("kill box", "airspace", 1, ["kill box"], O, ""),
    ("call sign", "airspace", 1, ["call sign"],
     "A word or group of letters and numbers that identifies a station, unit or aircraft on the radio.", ""),
    ("brevity code", "brevity", 1, ["brevity code"],
     "A single word or short phrase with an agreed meaning, used on the radio to pass information quickly.", ""),
    ("check-in", "airspace", 1, [],
     "The radio call in which a unit or aircraft reports to a controller that it has arrived and is ready, with its status.", "Check-out: the call when it leaves."),
    ("situation report", "c2", 1, ["situation report"], O, ""),
    ("spot report", "c2", 1, ["spot report"], O, "Often in SALUTE format (size, activity, location, unit, time, equipment)."),
    ("nine-line medical evacuation request", "medical", 1, [],
     "The standard nine-line radio message used to request evacuation of casualties, giving location, frequency, number of patients and other essentials.", ""),
    ("grid reference", "airspace", 1, [],
     "A map position given as letters and numbers of a grid system such as MGRS.", ""),
    ("bearing", "airspace", 1, ["bearing"],
     "The direction to an object measured clockwise from north, in degrees.", "Given with range: the distance to it."),
    ("time on target", "airspace", 1, ["time on target"], O, ""),
    # ---------------------------------------------------------------- brevity (starter mini-drill)
    ("BOGEY", "brevity", 1, ["BOGEY"], O, ""),
    ("BANDIT", "brevity", 1, ["BANDIT"], O, ""),
    ("HOSTILE", "brevity", 1, ["HOSTILE"], O, ""),
    ("FRIENDLY", "brevity", 1, ["FRIENDLY"], O, ""),
    ("UNKNOWN", "brevity", 1, ["UNKNOWN"],
     "Brevity: a contact whose identity has not been determined.", ""),
    ("SPLASH", "brevity", 1, ["SPLASH"], O, ""),
    ("SPIKE", "brevity", 1, ["SPIKE"], O, ""),
    ("NO JOY", "brevity", 1, ["NO JOY"], O, ""),
    ("TALLY", "brevity", 1, ["TALLY"], O, ""),
    ("BINGO", "brevity", 1, ["BINGO"], O, ""),
    ("CEASE FIRE", "brevity", 1, ["CEASE FIRE"], O, ""),
    ("WEAPONS (FREE / TIGHT / HOLD)", "brevity", 1, ["WEAPONS"], O, "The radio call that sets the weapons control status."),
    ("STAND BY", "brevity", 1, [],
     "Radio procedure word: wait, I will answer shortly.", "Procedure word (ACP 125), not a brevity code."),
    ("SAY AGAIN", "brevity", 1, ["SAY AGAIN"],
     "Radio procedure word: repeat your last message, or the part named.", "Procedure word (ACP 125)."),
    ("ROGER", "brevity", 1, ["ROGER"],
     "Radio procedure word: I have received your last message.", "Procedure word (ACP 125)."),
    ("WILCO", "brevity", 1, ["WILCO"],
     "Radio procedure word: I have received your message, understand it and will comply.", "Procedure word (ACP 125)."),
    ("BREAK BREAK", "brevity", 1, [],
     "Radio procedure words that interrupt traffic on a busy net to pass an urgent message.", "Procedure word (ACP 125)."),
    # ---------------------------------------------------------------- cross-cutting (starter list)
    ("authority", "c2", 1, ["authority"], "The right to give orders and make decisions within a defined area of responsibility.", ""),
    ("delegation of authority", "c2", 1, ["delegation of authority"], O, ""),
    ("coordinating authority", "c2", 1, ["coordinating authority"], O, ""),
    ("approval", "c2", 1, [], "Formal agreement by the person with authority that an action may go ahead.", ""),
    ("liaison", "c2", 1, ["liaison"], "Contact kept between units or organizations so that they understand each other and act together.", ""),
    ("interoperability", "c2", 1, ["interoperability"], O, ""),
    ("information sharing", "c2", 1, [], "Giving partners the information they need, within the limits of its classification and release rules.", ""),
    ("caveat", "c2", 1, [], "A restriction a nation places on how its forces may be used, or on who may see a piece of information.", ""),
    ("classification", "c2", 1, ["classification"], O, ""),
    ("release", "c2", 1, ["release"], "Formal permission to give classified or controlled information to a partner nation or organization.", "Releasable to = REL TO."),
    ("exercise", "c2", 1, ["exercise"], O, ""),
    ("drill", "c2", 1, [], "A short, repeated practice of a set procedure so that it becomes automatic.", ""),
    ("scenario", "c2", 1, [], "The imagined situation and events on which an exercise is built.", ""),
    ("lessons learned", "c2", 1, ["lessons learned", "lesson learned"], "Insights from an operation or exercise, recorded and acted on so that the next one goes better.", ""),
    ("after action review", "c2", 1, ["after action review", "after-action review"],
     "A structured discussion after an event or exercise about what was supposed to happen, what happened, why, and what to do differently.", ""),
]

# Extension by domain (priority 2/3): DoD Dictionary terms, looked up by name; no originals here.
EXTENSION: dict[str, list[tuple[str, int]]] = {
    "airspace": [
        ("airspace control authority", 2), ("airspace control order", 2), ("airspace control plan", 2), ("airspace management", 2),
        ("airspace coordination area", 2), ("air defense identification zone", 2), ("air corridor", 2), ("coordinating altitude", 2),
        ("restricted areas (air)", 3), ("high-density airspace control zone", 3), ("positive control", 2), ("procedural control", 2),
        ("air route", 3), ("air operations center", 2), ("air support operations center", 3), ("missile engagement zone", 2),
        ("joint engagement zone", 3), ("fighter engagement zone", 3), ("low-altitude missile engagement zone", 3),
        ("short-range air defense engagement zone", 2), ("high-altitude missile engagement zone", 3), ("air defense area", 3),
        ("air defense region", 3), ("air defense sector", 3), ("selective identification feature", 3), ("procedural identification", 3),
        ("combat identification", 2), ("combat air patrol", 2), ("track of interest", 2), ("airborne early warning", 2),
        ("threat warning", 2), ("air and missile defense", 2), ("integrated air and missile defense", 2), ("defensive counterair", 2),
        ("counterair", 3), ("point defense", 2), ("area air defense commander", 2), ("regional air defense commander", 3),
        ("sector air defense commander", 3), ("defended asset list", 2), ("missile defense", 3), ("air superiority", 3),
        ("close air support", 3), ("forward air controller", 3), ("joint terminal attack controller", 3), ("tactical air control party", 3),
        ("air liaison officer", 3), ("time-sensitive target", 3), ("target", 2), ("targeting", 3), ("collateral effect", 3),
        ("battle damage assessment", 2), ("no-fire area", 2), ("restrictive fire area", 3), ("fire support coordination line", 3),
        ("coordinated fire line", 3), ("air domain", 3), ("air defense", 2), ("aerospace defense", 3), ("air interdiction", 3),
        ("airborne alert", 3), ("ground alert", 3), ("threat assessment", 2),
    ],
    "roe": [
        ("engage", 2), ("engagement", 2), ("engagement authority", 2), ("target engagement authority", 3), ("weapons free zone", 2),
        ("weapons readiness state", 3), ("minimum force", 2), ("show of force", 2), ("nonlethal weapon", 2), ("cease engagement", 2),
        ("hold fire", 2), ("free-fire area", 3), ("final protective fire", 3), ("direct fire", 3),
    ],
    "ew": [
        ("electromagnetic warfare", 2), ("electromagnetic attack", 2), ("electromagnetic protection", 2), ("electromagnetic support", 2),
        ("electromagnetic interference", 2), ("electromagnetic spectrum operations", 2), ("electromagnetic spectrum management", 3),
        ("electromagnetic compatibility", 3), ("electromagnetic environment", 3), ("electromagnetic intrusion", 3),
        ("electromagnetic probing", 3), ("electromagnetic pulse", 3), ("emission control", 2), ("emission security", 3),
        ("communications security", 2), ("transmission security", 3), ("joint restricted frequency list", 3), ("PROTECTED frequencies", 3),
        ("electromagnetic battle management", 3), ("electromagnetic vulnerability", 3), ("electromagnetic hardening", 3),
        ("countermeasures", 2), ("electro-optical-infrared countermeasure", 3), ("electromagnetic spectrum superiority", 3),
    ],
    "base-defense": [
        ("base defense zone", 2), ("base boundary", 2), ("base cluster", 2), ("base cluster operations center", 3), ("physical security", 2),
        ("security", 2), ("mobile security force", 2), ("tactical combat force", 3), ("joint security area", 3),
        ("joint security coordinator", 3), ("joint security coordination center", 3), ("terrorism threat level", 2),
        ("threat analysis", 3), ("improvised explosive device", 2), ("vehicle-borne improvised explosive device", 2),
        ("explosive ordnance disposal", 2), ("explosive hazard", 3), ("explosive ordnance", 3), ("counter-improvised explosive device", 3),
        ("area damage control", 2), ("collective protection", 3), ("individual protective equipment", 3),
        ("mission-oriented protective posture", 2), ("defense critical infrastructure", 3), ("cooperative security location", 3),
        ("forward operating base", 2), ("main operating base", 3), ("intermediate staging base", 3), ("internal security", 3),
        ("countersurveillance", 3), ("operations security", 2), ("force protection working group", 3), ("antiterrorism", 2),
        ("base support installation", 3), ("joint base", 3), ("dynamic threat assessment", 3), ("countermobility", 3),
        ("improvised threat", 3), ("protection", 3), ("force health protection", 3),
    ],
    "c2": [
        ("command and control", 2), ("command", 2), ("control", 3), ("operational control", 2), ("tactical control", 2),
        ("administrative control", 3), ("chain of command", 2), ("commander's intent", 2), ("commander's critical information requirement", 3),
        ("mission command", 2), ("unity of command", 3), ("direct liaison authorized", 3), ("interagency coordination", 3),
        ("multinational force", 2), ("multinational force commander", 3), ("classified information", 2), ("security review", 3),
        ("command net", 3), ("friendly force tracking", 3), ("warning order", 2), ("alert order", 3), ("supported commander", 3),
        ("supporting commander", 3), ("joint force commander", 3), ("joint task force", 3), ("command relationships", 3),
        ("decentralized control", 3), ("centralized control", 3), ("civil affairs", 3), ("public affairs", 3),
        ("community engagement", 3), ("military engagement", 3), ("security cooperation", 3), ("security force assistance", 3),
    ],
    "logistics": [
        ("logistics", 2), ("supply", 3), ("common-user logistics", 3), ("multinational logistics", 2), ("base operating support", 3),
        ("host-nation support", 2), ("force beddown", 3), ("staging base", 3), ("movement control team", 3),
        ("contractors authorized to accompany the force", 3), ("air mobility", 3), ("intratheater airlift", 3), ("airdrop", 3),
    ],
    "medical": [
        ("casualty", 2), ("casualty evacuation", 2), ("aeromedical evacuation", 2), ("medical evacuation", 2), ("mass casualty", 2),
        ("roles of medical care", 3), ("medical treatment facility", 3), ("tactical combat casualty care", 2),
        ("combat and operational stress control", 3), ("medical regulating", 3), ("personal protective equipment", 3),
    ],
    "hadr": [
        ("foreign humanitarian assistance", 2), ("foreign disaster relief", 2), ("foreign disaster", 3), ("natural disaster", 3),
        ("humanitarian and civic assistance", 3), ("humanitarian operations center", 3), ("humanitarian assistance coordination center", 3),
        ("disaster assistance response team", 3), ("noncombatant evacuation operation", 2), ("civil-military operations center", 2),
        ("dislocated civilian", 2), ("evacuation", 3), ("humanitarian mine action", 3),
    ],
    "brevity": [
        ("JOKER", 2), ("WINCHESTER", 2), ("PICTURE", 2), ("DECLARE", 2), ("CLEAN", 3),
        ("BLIND", 2), ("VISUAL", 2), ("ABORT", 2), ("CHECK FIRE(ING)", 2), ("HOLD FIRE (brevity)", 2), ("MARK", 3), ("MUSIC", 3), ("BUZZER", 3),
        ("STROBE", 3), ("NAKED", 3), ("SKATE", 3), ("BUSTER", 3), ("GATE", 3), ("PUSH", 3), ("SNAP", 3), ("SPOT", 3),
        ("CONTACT", 2), ("LOST LOCK", 3), ("FADED", 3), ("POP", 3), ("SORTED", 3), ("STATUS", 3), ("TRACK (brevity)", 3), ("SAM", 3),
        ("THREAT", 2), ("ENGAGED", 2), ("COMMIT", 3), ("BRACKET", 3), ("BREAK (direction)", 3), ("KILL", 2), ("SCRAM", 3),
        ("LEAKER", 2),
    ],
}
# fmt: on
