"""gate_content (BRIEF §11.1, Phase 6 onward): pack counts against the §5.3 launch targets for every language.

A shortfall does not fail the gate; it is logged with the exact drafting command that closes it (BRIEF §11.2 Phase 6),
and the table is written to docs/CONTENT_STATUS.md. The gate fails only when a pack is missing, an item is malformed
(strict validation runs separately in gate_content.sh), or a listening passage has neither a clip nor a run-time voice.
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(REPO / "tools"))
sys.path.insert(0, str(REPO / "tools" / "opi"))

from draft_opi import DOMAINS, TOPICS_PER_DOMAIN

import langtext

LEVELS = ["0+", "1", "1+", "2", "2+", "3"]
PER_BAND, ITEMS_PER_PASSAGE, QUESTIONS, ROLEPLAYS = 12, 3, 80, 24
TOPICS = len(DOMAINS) * TOPICS_PER_DOMAIN
PACKS = REPO / "content" / "packs"
# Languages whose listening passages are spoken at run time by the OS voice when no clip exists (D-013).
PIPER = {v["language"] for v in json.loads((REPO / "voices" / "manifest.json").read_text())["voices"]}


def main() -> int:
    rows, gaps, errors = [], [], []
    for lang in langtext.LANGS:
        exam_f, opi_f = PACKS / lang / "exam.json", PACKS / lang / "opi.json"
        if not exam_f.is_file() or not opi_f.is_file():
            errors.append(f"{lang}: pack missing (run packs/build_packs.py --language {lang})")
            continue
        exam, opi = json.loads(exam_f.read_text()), json.loads(opi_f.read_text())
        row = {"lang": lang}
        for skill in ("reading", "listening"):
            bank = exam[skill]
            per = {lv: sum(1 for p in bank["passages"] if p["level"] == lv) for lv in LEVELS}
            row[skill] = (sum(per.values()), len(bank["items"]))
            short = {lv: PER_BAND - n for lv, n in per.items() if n < PER_BAND}
            if short:
                gaps.append(f"{lang} {skill}: short {sum(short.values())} passages "
                            f"({', '.join(f'{lv}:{n}' for lv, n in short.items())}) — close with: "
                            f"cd tools && uv run --group content python items/gen_dlpt.py fill --language {lang} --skill {skill} --per-band {PER_BAND}")
        listening = [p["id"] for p in exam["listening"]["passages"]]
        clips = sum(1 for p in listening if p in exam.get("audio", {}))
        row["audio"] = f"{clips}/{len(listening)}" + ("" if lang in PIPER else " (OS voice)")
        missing = len(listening) - clips
        if missing and lang in PIPER:
            gaps.append(f"{lang} listening: {missing} passages without a clip (spoken at run time by Piper) — close with: "
                        f"cd tools && uv run --group content python packs/render_audio.py --language {lang}")
        elif missing:
            print(f"{lang} listening: {missing} passages use the OS voice at run time (no bundled voice, D-013)")
        q, r, t = len(opi["questions"]), len(opi["rolePlays"]), len(opi["topics"])
        row["opi"] = (q, r, t)
        if q < QUESTIONS or r < ROLEPLAYS or t < TOPICS:
            gaps.append(f"{lang} opi: {q}/{QUESTIONS} questions, {r}/{ROLEPLAYS} role-plays, {t}/{TOPICS} topics — close with: "
                        f"cd tools && uv run --group content python opi/draft_opi.py --language {lang}")
        row["llm"] = sum(1 for s in ("reading", "listening") for p in exam[s]["passages"] if p.get("source") == "llm")
        row["verified"] = sum(1 for s in ("reading", "listening") for p in exam[s]["passages"] if p.get("verified"))
        rows.append(row)

    target = f"{6 * PER_BAND} / {6 * PER_BAND * ITEMS_PER_PASSAGE}"
    intro = ("Generated by `tools/gates/check_content.py` (gate_content). Targets from BRIEF §5.3: "
             f"reading and listening {target} passages/items per language, OPI {QUESTIONS} questions + {ROLEPLAYS} role-plays + "
             f"{TOPICS} topics. AI-drafted content is `source = \"llm\"` and badged until reviewed.")
    md = ["# Content status", "", intro, "",
          "| Language | Reading (passages / items) | Listening (passages / items) | Listening audio | OPI (q / rp / topics) | AI-drafted passages | Verified |",
          "|---|---|---|---|---|---|---|"]
    for r in rows:
        md.append(f"| {r['lang']} | {r['reading'][0]} / {r['reading'][1]} | {r['listening'][0]} / {r['listening'][1]} | {r['audio']} | "
                  f"{' / '.join(map(str, r['opi']))} | {r['llm']} | {r['verified']} |")
    md += ["", "## Shortfalls and the commands that close them", ""] + ([f"- {g}" for g in gaps] or ["None."])
    (REPO / "docs" / "CONTENT_STATUS.md").write_text("\n".join(md) + "\n", encoding="utf-8")
    print("\n".join(md))
    for e in errors:
        print(f"ERROR {e}", file=sys.stderr)
    return 1 if errors else 0


if __name__ == "__main__":
    raise SystemExit(main())
