"""JLPT item bank pipeline (BRIEF §5.11): rule-based generation, validation, and LLM drafting.

Commands (run from tools/):
  uv run python items/gen_jlpt.py generate --packs ../content/packs --out items/bank/jlpt_generated.json
  uv run python items/gen_jlpt.py validate items/bank/jlpt_generated.json items/bank/jlpt_authored.json
  uv run python items/gen_jlpt.py draft --endpoint http://localhost:11434/v1 --model qwen3:8b \
      --level N3 --type paraphrase --count 10 --out items/bank/drafts/n3-paraphrase.json

Bank format: docs/CONTENT_PACKS.md "Exam item banks". Blueprint: items/jlpt_blueprints.json.

`generate` is deterministic for a given set of packs (no randomness beyond seeded shuffles keyed by item id) and
builds only what data supports honestly, all with source="generated":
  kanji_reading      Tatoeba sentence, target word underlined; choices are its reading + 3 wrong readings
                     (other on/kun readings of its kanji, voicing / long vowel / っ variants), none of which JMdict
                     lists as a reading of the written form.
  orthography        Same, reversed: the word in kana underlined; choices are written forms, distractors swap one
                     kanji for a same-reading or look-alike kanji and are not JMdict spellings of that reading.
  context            Tatoeba sentence with the word blanked; distractors are same-level, same-POS words inflected
                     like the key, rejected when Tatoeba attests them with the same neighbour or they share a
                     gloss with the key.
  grammar_form       grammar.sqlite Tatoeba example with the construction blanked; distractors are other points'
                     constructions (related points first, then the same level), minus near-synonyms and
                     attested fits. Level-agnostic: every level present in grammar.sqlite is generated.
  sentence_assembly  ★ format from a grammar example split into bunsetsu (tokenizer.sqlite).

Markup used in stems (the app renders these; same convention in the authored bank):
  <u>…</u>     underlined target (kanji_reading, orthography, paraphrase; also reading passages)
  （　　）     blank to fill (context, grammar_form, word_formation): U+FF08, two U+3000, U+FF09
  ＿＿＿        a sentence_assembly slot (three U+FF3F); ＿★＿ the starred slot. Slots are separated by U+3000,
               e.g. "彼は　＿＿＿　＿＿＿　＿★＿　＿＿＿　です。"; the answer is the chunk for ＿★＿.
  ［1］…       numbered blanks in a text_grammar passage body; the item's stem is the marker itself.
  | a | b |    table rows in info_retrieval passage bodies (first row is the header).
refs: "g:<grammar id>", "v:<JMdict id>", and "t:<Tatoeba sentence id>" for attribution of the source sentence.
"""

from __future__ import annotations

import argparse
import json
import random
import re
import sqlite3
import sys
import time
import unicodedata
import urllib.request
from collections import Counter, defaultdict
from dataclasses import dataclass, field
from pathlib import Path

HERE = Path(__file__).resolve().parent
REPO = HERE.parents[1]
BLUEPRINTS = HERE / "jlpt_blueprints.json"
DEFAULT_PACKS = REPO / "content" / "packs"

LEVELS = ["N5", "N4", "N3", "N2", "N1"]
GENERATED_TYPES = ["kanji_reading", "orthography", "context", "grammar_form", "sentence_assembly"]
THREE_CHOICE_TYPES = {"utterance", "quick_response"}
EXAMS = {"JLPT", "DLPT_READING", "DLPT_LISTENING"}
VOICES = {"female", "male", "narrator"}

BLANK = "（　　）"
SLOT = "＿＿＿"
STAR = "＿★＿"
U_OPEN, U_CLOSE = "<u>", "</u>"
TG_MARK = re.compile(r"［(\d+)］")

GENERATED_BANK = {
    "bank": "jlpt-generated",
    "title": "JLPT practice: rule-generated items",
    "license": "CC BY-SA 4.0",
    "attribution": (
        "Generated by Tsumugi's tools/items/gen_jlpt.py from Tatoeba sentences (CC BY 2.0 FR, tatoeba.org; "
        "sentence ids in refs as t:<id>), JMdict and KANJIDIC2 (EDRDG, CC BY-SA 4.0), mecab-ipadic (NAIST) and "
        "the Tsumugi grammar pack."
    ),
}


# --- text helpers -------------------------------------------------------------------------------------------


def nfc(s: str) -> str:
    return unicodedata.normalize("NFC", s)


def hira(s: str) -> str:
    return "".join(chr(ord(c) - 0x60) if "ァ" <= c <= "ヶ" else c for c in s)


def is_kanji(c: str) -> bool:
    o = ord(c)
    return 0x4E00 <= o <= 0x9FFF or 0x3400 <= o <= 0x4DBF or 0x20000 <= o <= 0x2FFFF or c in "々〆"


def is_hira(c: str) -> bool:
    return "ぁ" <= c <= "ゖ" or c == "ー"


def is_kana(c: str) -> bool:
    return is_hira(c) or "ァ" <= c <= "ヺ"


def has_kanji(s: str) -> bool:
    return any(is_kanji(c) for c in s)


def strip_markup(s: str) -> str:
    return s.replace(U_OPEN, "").replace(U_CLOSE, "")


def level_num(level: str) -> int:
    return int(level[1])


def seeded(key: str) -> random.Random:
    return random.Random(key)  # str seeds are hashed with SHA-512: stable across runs and platforms


VOICE = dict(zip("かきくけこさしすせそたちつてとはひふへほ", "がぎぐげござじずぜぞだぢづでどばびぶべぼ"))
UNVOICE = {v: k for k, v in VOICE.items()} | dict(zip("ぱぴぷぺぽ", "はひふへほ"))
HALF = dict(zip("はひふへほ", "ぱぴぷぺぽ"))
O_ROW = set("おこごそぞとどのほぼぽもよろょ")
E_ROW = set("えけげせぜてでねへべぺめれ")
SOKUON_OK = set("かきくけこさしすせそたちつてとぱぴぷぺぽ")


def reading_variants(segs: list[str]) -> list[str]:
    """Plausible misreadings of a reading split into per-kanji segments: voicing / handakuten at a segment start,
    long vowel added or dropped at a segment end, っ at a segment boundary, big ゃゅょ. The kind of confusion
    learners actually make (けいざい/げいざい, しょうねん/しょねん, がっこう/がくこう)."""
    out: list[str] = []

    def emit(i: int, seg: str) -> None:
        out.append("".join(seg if j == i else x for j, x in enumerate(segs)))

    for i, seg in enumerate(segs):
        if not seg:
            continue
        c = seg[0]
        if c in VOICE:
            emit(i, VOICE[c] + seg[1:])
        if c in UNVOICE:
            emit(i, UNVOICE[c] + seg[1:])
        if c in HALF and i > 0:
            emit(i, HALF[c] + seg[1:])
        last = seg[-1]
        long_u = last == "う" and (seg[-2:-1] in O_ROW or seg[-2:-1] == "ゅ")
        long_i = last == "い" and seg[-2:-1] in E_ROW
        if len(seg) >= 2 and (long_u or long_i):
            emit(i, seg[:-1])
        elif last in O_ROW or last == "ゅ":
            emit(i, seg + "う")
        elif last in E_ROW:
            emit(i, seg + "い")
        nxt = segs[i + 1] if i + 1 < len(segs) else ""
        if nxt and nxt[0] in SOKUON_OK and len(seg) >= 2 and last in "つくちき":
            emit(i, seg[:-1] + "っ")
        if last == "っ":
            emit(i, seg[:-1] + "つ")
            emit(i, seg[:-1] + "く")
        for k, ch in enumerate(seg):
            if ch in "ゃゅょ":
                emit(i, seg[:k] + {"ゃ": "や", "ゅ": "ゆ", "ょ": "よ"}[ch] + seg[k + 1:])
    r = "".join(segs)
    seen, res = {r}, []
    for v in out:
        if v not in seen and v and v[0] not in "っんー" and not is_small(v[0]):
            seen.add(v)
            res.append(v)
    return res


GOJUON = ["あいうえお", "かきくけこ", "がぎぐげご", "さしすせそ", "ざじずぜぞ", "たちつてと", "だぢづでど",
          "なにぬねの", "はひふへほ", "ばびぶべぼ", "ぱぴぷぺぽ", "まみむめも", "らりるれろ"]
ROW_OF = {c: row for row in GOJUON for c in row}


def vowel_shifts(r: str) -> list[str]:
    """Readings one vowel away (ほん→はん, ひと→ふと): the fallback pool when a word has few other readings."""
    out = []
    for i, c in enumerate(r):
        if c in ROW_OF and not (i + 1 < len(r) and is_small(r[i + 1])):
            out += [r[:i] + x + r[i + 1:] for x in ROW_OF[c] if x != c]
    return out


def is_small(c: str) -> bool:
    return c in "ぁぃぅぇぉゃゅょゎっ"


def split_tail(surface: str, reading: str) -> tuple[str, str, str, str] | None:
    """Split a written span and its hiragana reading into (kana head, kanji core, its reading, kana tail),
    e.g. ("起きます", "おきます") -> ("", "起", "お", "きます"); ("お茶", "おちゃ") -> ("お", "茶", "ちゃ", "")."""
    h = 0
    while h < len(surface) and h < len(reading) and not is_kanji(surface[h]) and surface[h] == reading[h]:
        h += 1
    t = 0
    while (t < len(surface) - h and t < len(reading) - h and not is_kanji(surface[-1 - t])
           and surface[-1 - t] == reading[-1 - t]):
        t += 1
    core, core_r = surface[h:len(surface) - t], reading[h:len(reading) - t]
    if not core or not core_r or not all(is_kanji(c) or c in "ヶ" for c in core):
        return None
    return surface[:h], core, core_r, surface[len(surface) - t:]


# --- blueprint ----------------------------------------------------------------------------------------------


def load_blueprint(path: Path = BLUEPRINTS) -> dict[str, dict[str, int]]:
    """level ("N5".."N1") -> {item type: count in one full mock}."""
    data = json.loads(path.read_text(encoding="utf-8"))
    out: dict[str, dict[str, int]] = {}
    for lv in data["levels"]:
        types: dict[str, int] = {}
        for sec in lv["sections"]:
            for it in sec["items"]:
                types[it["type"]] = types.get(it["type"], 0) + it["count"]
        out[f"N{lv['level']}"] = types
    return out


def type_titles(path: Path = BLUEPRINTS) -> dict[str, str]:
    data = json.loads(path.read_text(encoding="utf-8"))
    return {it["type"]: it["title"] for lv in data["levels"] for s in lv["sections"] for it in s["items"]}


# --- packs --------------------------------------------------------------------------------------------------


@dataclass
class Word:
    id: int
    level: int
    rank: int
    kanji: list[str]
    kana: list[str]
    readings_for: dict[str, list[str]]  # kanji form -> hiragana readings
    pos: list[str]  # JMdict pos tags of the first sense
    uk: bool
    glosses: list[str]
    kana_raw: list[str] = field(default_factory=list)  # as written in JMdict (katakana kept), for display

    @property
    def written(self) -> str:
        return (self.kana_raw or self.kana)[0] if (self.uk or not self.kanji) else self.kanji[0]


BAD_KANJI_TAGS = {"rK", "iK", "oK", "sK", "ateji", "ik", "io"}
BAD_POS = {"n-pr", "ctr", "num", "pn", "pref", "suf", "n-suf", "exp", "int", "conj", "prt", "aux", "aux-v",
           "aux-adj", "cop", "unc"}


def coarse_pos(tags: list[str]) -> str:
    t = set(tags)
    if any(x.startswith("v5") or x in {"v1", "vk", "vs-i", "vs-s", "vz"} for x in t):
        return "verb"
    if "adj-i" in t or "adj-ix" in t:
        return "adj-i"
    if "adj-na" in t:
        return "adj-na"
    if "adv" in t and not ({"n", "n-adv"} & t):
        return "adv"
    if "n" in t or "vs" in t:
        return "noun"
    return "other"


class Packs:
    def __init__(self, packs: Path):
        self.dir = packs
        self.dict = sqlite3.connect(f"file:{packs / 'dictionary.sqlite'}?mode=ro", uri=True)
        g = packs / "grammar.sqlite"
        self.grammar = sqlite3.connect(f"file:{g}?mode=ro", uri=True) if g.exists() else None
        self._readings: dict[str, set[str]] = {}
        self._kanji: dict[str, tuple[int | None, list[str], list[str]]] = {}
        self.words: dict[int, Word] = {}
        self._load_words()
        self.sentences: dict[int, tuple[str, str, int | None]] = {
            sid: (ja, en, lv) for sid, ja, en, lv in self.dict.execute("SELECT id, ja, en, jlpt FROM sentence")
        }
        self.word_sentences: dict[int, list[int]] = defaultdict(list)
        for eid, sid in self.dict.execute("SELECT entry_id, sentence_id FROM sentence_word ORDER BY entry_id, sentence_id"):
            if eid in self.words:
                self.word_sentences[eid].append(sid)
        self.corpus = "\n" + "\n".join(ja for ja, _, _ in self.sentences.values()) + "\n"
        self._lattice = None
        self.stems: set[tuple] = set()

    def claim_stem(self, typ: str, stem: str, choices: list[str]) -> bool:
        """Register a stem bank-wide; False if it is already used (same rule as the validator)."""
        key = stem_key(typ, "", stem, "", choices)
        if key in self.stems:
            return False
        self.stems.add(key)
        return True

    @property
    def lattice(self):
        if self._lattice is None:
            from lattice import Lattice

            self._lattice = Lattice(self.dir / "tokenizer.sqlite")
        return self._lattice

    def _load_words(self) -> None:
        rows = self.dict.execute("SELECT id, jlpt, rank FROM entry WHERE jlpt IS NOT NULL ORDER BY rank, id").fetchall()
        ids = [r[0] for r in rows]
        kanji, kana, senses = defaultdict(list), defaultdict(list), {}
        for chunk in (ids[i:i + 900] for i in range(0, len(ids), 900)):
            q = ",".join("?" * len(chunk))
            for eid, text, tags in self.dict.execute(
                f"SELECT entry_id, text, tags FROM entry_kanji WHERE entry_id IN ({q}) ORDER BY entry_id, ord", chunk
            ):
                if not (set(json.loads(tags or "[]")) & BAD_KANJI_TAGS):
                    kanji[eid].append(text)
            for eid, text, tags, applies in self.dict.execute(
                f"SELECT entry_id, text, tags, applies_to FROM entry_kana WHERE entry_id IN ({q}) ORDER BY entry_id, ord",
                chunk,
            ):
                if not (set(json.loads(tags or "[]")) & BAD_KANJI_TAGS):
                    kana[eid].append((hira(text), json.loads(applies) if applies else ["*"], text))
            for eid, pos, glosses, misc in self.dict.execute(
                f"SELECT entry_id, pos, glosses, misc FROM sense WHERE entry_id IN ({q}) AND ord = 0", chunk
            ):
                senses[eid] = (json.loads(pos or "[]"), json.loads(glosses or "[]"), json.loads(misc or "[]"))
        for eid, jlpt, rank in rows:
            if eid not in senses or not kana[eid]:
                continue
            pos, glosses, misc = senses[eid]
            rf = {k: [r for r, ap, _ in kana[eid] if "*" in ap or k in ap] for k in kanji[eid]}
            self.words[eid] = Word(eid, jlpt, rank, kanji[eid], [r for r, _, _ in kana[eid]], rf, pos,
                                   "uk" in misc, glosses, [t for _, _, t in kana[eid]])

    def readings_of(self, written: str) -> set[str]:
        """Every hiragana reading JMdict gives the written form (all entries, not only JLPT-tagged ones)."""
        if written not in self._readings:
            out = set()
            for eid, in self.dict.execute("SELECT DISTINCT entry_id FROM entry_kanji WHERE text = ?", (written,)):
                for text, applies in self.dict.execute(
                    "SELECT text, applies_to FROM entry_kana WHERE entry_id = ?", (eid,)
                ):
                    ap = json.loads(applies) if applies else ["*"]
                    if "*" in ap or written in ap:
                        out.add(hira(text))
            self._readings[written] = out
        return self._readings[written]

    def word_readings(self) -> set[str]:
        if not hasattr(self, "_word_readings"):
            self._word_readings = {r for w in self.words.values() for r in w.kana}
        return self._word_readings

    def kanji_info(self, k: str) -> tuple[int | None, list[str], list[str]]:
        """(jlpt_new, on readings in hiragana, kun stems in hiragana)."""
        if k not in self._kanji:
            row = self.dict.execute("SELECT jlpt_new, onyomi, kunyomi FROM kanji WHERE literal = ?", (k,)).fetchone()
            if row is None:
                self._kanji[k] = (None, [], [])
            else:
                on = [hira(x) for x in json.loads(row[1] or "[]")]
                kun = sorted({x.split(".")[0].strip("-") for x in json.loads(row[2] or "[]")} - {""})
                self._kanji[k] = (row[0], on, kun)
        return self._kanji[k]

    def furigana(self, text: str, reading: str) -> list[tuple[str, str]] | None:
        row = self.dict.execute("SELECT segments FROM furigana WHERE text = ? AND reading = ?", (text, reading)).fetchone()
        if not row:
            return None
        segs = []
        for part in row[0].split("|"):
            ruby, _, rt = part.partition("=")
            segs.append((ruby, rt or ruby))
        return segs

    def kanji_by_reading(self) -> dict[str, list[str]]:
        if not hasattr(self, "_by_reading"):
            idx: dict[str, list[str]] = defaultdict(list)
            for lit, jl, on, kun in self.dict.execute(
                "SELECT literal, jlpt_new, onyomi, kunyomi FROM kanji WHERE jlpt_new IS NOT NULL ORDER BY freq, literal"
            ):
                rs = {hira(x) for x in json.loads(on or "[]")}
                rs |= {x.split(".")[0].strip("-") for x in json.loads(kun or "[]")}
                for r in rs - {""}:
                    idx[r].append(lit)
            self._by_reading = idx
        return self._by_reading

    def components(self, k: str) -> set[str]:
        return {r for r, in self.dict.execute("SELECT radical FROM kanji_component WHERE kanji = ?", (k,))}

    def lookalikes(self, k: str) -> list[str]:
        """JLPT-list kanji sharing a distinctive component with k (components in > 120 JLPT kanji, like 口 or
        一, don't count), most shared first."""
        if not hasattr(self, "_comp_index"):
            idx: dict[str, list[str]] = defaultdict(list)
            for kanji, rad in self.dict.execute(
                "SELECT c.kanji, c.radical FROM kanji_component c JOIN kanji k ON k.literal = c.kanji "
                "WHERE k.jlpt_new IS NOT NULL ORDER BY k.freq, c.kanji"
            ):
                idx[rad].append(kanji)
            self._comp_index = {r: ks for r, ks in idx.items() if len(ks) <= 120}
        score: Counter = Counter()
        for rad in self.components(k):
            for other in self._comp_index.get(rad, []):
                if other != k:
                    score[other] += 1
        return [o for o, _ in sorted(score.items(), key=lambda x: (-x[1], x[0]))]

    def attested(self, left: str, d: str, right: str = "") -> bool:
        """True if Tatoeba has `left + d + right` (a sign that d fits the slot)."""
        return (left + d + right) in self.corpus


# --- generation: vocabulary ---------------------------------------------------------------------------------


@dataclass
class Span:
    start: int
    end: int
    surface: str
    reading: str  # hiragana
    head: object  # lattice Token of the content word
    tokens: list = field(default_factory=list)


AUX_OK = {"ます", "た", "ない", "たい", "だ", "ん", "う", "よう", "です", "まし", "でし", "なかっ", "ませ", "たかっ"}


def find_span(tokens, word: Word, sentence: str) -> Span | None:
    """Locate `word` in a tokenized sentence: the content token(s) plus trailing auxiliaries (ます, た, ない…).
    The tokenizer's reading must be a JMdict reading of the entry, which disambiguates homographs."""
    pos = coarse_pos(word.pos)
    forms = set(word.kanji) | set(word.kana) | set(word.kana_raw)
    for i, t in enumerate(tokens):
        j = None
        if pos in {"verb", "adj-i"}:
            if t.pos1 in {"動詞", "形容詞"} and t.base in forms:
                j = i + 1
        else:
            acc = ""
            for k in range(i, min(i + 4, len(tokens))):
                acc += tokens[k].surface
                if acc in forms:
                    j = k + 1
                    break
                if len(acc) >= max(map(len, forms)):
                    break
        if j is None:
            continue
        head = tokens[i:j]
        if any(not x.reading for x in head):
            return None
        # check the reading against the entry
        if pos in {"verb", "adj-i"}:
            parts = split_tail(t.surface, hira(t.reading))
            base_parts = None
            if t.base in word.kanji:
                # dictionary-form reading = core reading + base okurigana
                if parts:
                    base_parts = parts[1], parts[2]
                    base_tail = t.base[len(parts[0]) + len(parts[1]):]
                    if not t.base.startswith(parts[0] + parts[1]):
                        return None
                    dict_r = parts[2] + base_tail
                    if hira(parts[0]) + dict_r not in word.readings_for.get(t.base, []):
                        return None
            elif t.base not in word.kana and t.base not in word.kana_raw:
                return None
            del base_parts
        else:
            r = hira("".join(x.reading for x in head))
            surf = "".join(x.surface for x in head)
            ok = r in word.kana if (surf in word.kana or surf in word.kana_raw) else r in word.readings_for.get(surf, [])
            if not ok:
                return None
        # trailing auxiliaries
        while pos in {"verb", "adj-i"} and j < len(tokens) and (
            (tokens[j].pos1 == "助動詞" and tokens[j].surface in AUX_OK)
            or (tokens[j].pos1 == "動詞" and tokens[j].pos2 == "接尾")  # passive/causative れる・せる
            or (tokens[j].pos1 == "名詞" and tokens[j].pos2 == "接尾" and tokens[j].surface in {"さ", "み"})
            or (tokens[j].pos1 == "助詞" and tokens[j].pos2 == "接続助詞" and tokens[j].surface in {"て", "で", "ば"})
        ):
            j += 1
            if tokens[j - 1].pos1 == "助詞":
                break
        if tokens[j - 1].conj_form.startswith(("未然", "ガル")):
            return None  # the underline would end mid-word
        toks = tokens[i:j]
        surface = "".join(x.surface for x in toks)
        if sentence.count(surface) != 1:
            return None
        return Span(toks[0].start, toks[-1].end, surface, hira("".join(x.reading for x in toks)), t, toks)
    return None


def usable_sentences(p: Packs, word: Word, level: int, used: set[int], max_len: int = 36) -> list[int]:
    """Sentences whose every tagged word is at `level` or easier (`level` may be lowered by one in a relaxed
    second pass; the validator then flags the harder word)."""
    out = []
    for sid in p.word_sentences.get(word.id, []):
        ja, _, lv = p.sentences[sid]
        if sid in used or lv is None or lv < level or not (8 <= len(ja) <= max_len):
            continue
        if any(c in ja for c in "<>＿（）()「」『』"):
            continue
        out.append(sid)
    return sorted(out, key=lambda s: (len(p.sentences[s][0]), s))


def kanji_ok(p: Packs, written: str, level: int) -> bool:
    """Every kanji is on a JLPT kanji list at most one level above (the community N5 list has only ~80 kanji,
    fewer than the N5 vocabulary uses; N1 accepts any kanji)."""
    for c in written:
        if is_kanji(c):
            jl = p.kanji_info(c)[0]
            if level > 1 and (jl is None or jl < level - 1):
                return False
    return True


def wrong_readings(p: Packs, head: str, core: str, core_r: str, tail: str, dict_written: str,
                   dict_tail: str, key: str) -> list[str]:
    """Up to 3 wrong readings of head+core+tail, preferring real readings of the same kanji."""
    valid = p.readings_of(dict_written) | p.readings_of(head + core + tail)
    base_head = hira(head)
    segs = p.furigana(core, core_r) if len(core) > 1 else [(core, core_r)]
    if not segs or "".join(r for _, r in segs) != core_r:
        segs = None
    from_kanji: list[str] = []
    if segs:
        for i, (ruby, rt) in enumerate(segs):
            if len(ruby) != 1 or not is_kanji(ruby):
                continue
            _, on, kun = p.kanji_info(ruby)
            # compounds and okurigana words: other on-readings (起きます→ききます); lone kanji: kun too (人→じん)
            alts = on if (len(segs) > 1 or tail) else on + kun
            for alt in alts:
                if alt and alt != rt:
                    from_kanji.append("".join(a if j != i else alt for j, (_, a) in enumerate(segs)))
    variants = reading_variants([r for _, r in segs] if segs else [core_r])
    rng = seeded(key)
    rng.shuffle(from_kanji)
    rng.shuffle(variants)
    shifts = vowel_shifts(core_r)
    rng.shuffle(shifts)
    shifts.sort(key=lambda x: x not in p.word_readings())  # real words look more plausible
    out: list[str] = []
    pools = [from_kanji, variants]
    turn = 0
    while len(out) < 3 and (any(pools) or shifts):
        if any(pools):
            pool = pools[turn % 2] if pools[turn % 2] else pools[(turn + 1) % 2]
            turn += 1
        else:
            pool = shifts
        cand = pool.pop(0)
        full = base_head + cand + hira(tail)
        if abs(len(cand) - len(core_r)) > 2 or (len(core_r) >= 2 and len(cand) < 2):
            continue
        if cand == core_r or full in out or base_head + cand + dict_tail in valid or full in valid:
            continue
        if not all(is_hira(c) for c in cand) or re.search(r"[んっ][っんゃゅょぁぃぅぇぉ]", full):
            continue
        out.append(full)
    return out


def wrong_spellings(p: Packs, head: str, core: str, core_r: str, tail: str, dict_tail: str,
                    dict_reading: str, level: int, key: str) -> list[str]:
    """Up to 3 wrong written forms: one kanji swapped for a same-reading or look-alike kanji."""
    segs = p.furigana(core, core_r) if len(core) > 1 else [(core, core_r)]
    if not segs or "".join(r for _, r in segs) != core_r:
        return []
    by_r = p.kanji_by_reading()
    cands: list[tuple[int, str]] = []
    for i, (ruby, rt) in enumerate(segs):
        if len(ruby) != 1 or not is_kanji(ruby):
            continue
        comps = p.components(ruby)
        homophones = set(by_r.get(rt, []))
        pool = set(homophones) | set(p.lookalikes(ruby)[:12])
        # rendaku / sokuon variants of the segment reading still sound "the same" to a learner
        if rt and rt[0] in UNVOICE:
            homophones |= set(by_r.get(UNVOICE[rt[0]] + rt[1:], []))
        if rt.endswith("っ"):
            homophones |= set(by_r.get(rt[:-1] + "つ", [])) | set(by_r.get(rt[:-1] + "く", []))
        pool |= homophones
        for k in sorted(pool):
            if k == ruby:
                continue
            jl = p.kanji_info(k)[0]
            if jl is None or jl < max(level - 1, 1):
                continue
            score = 2 * len(comps & p.components(k)) + (3 if k in homophones else 0) + (1 if jl == p.kanji_info(ruby)[0] else 0)
            new = "".join(r if j != i else k for j, (r, _) in enumerate(segs))
            cands.append((-score, new))
    rng = seeded(key)
    rng.shuffle(cands)
    cands.sort(key=lambda x: x[0])
    out: list[str] = []
    for _, new in cands:
        full = head + new + tail
        if full in out or dict_reading in p.readings_of(head + new + dict_tail):
            continue
        out.append(full)
        if len(out) == 3:
            break
    return out


def answer_slot(key: str, index: int, n: int = 4) -> int:
    """Balanced, deterministic key positions: each block of n consecutive items uses every position once, in a
    seeded order."""
    perm = list(range(n))
    seeded(f"{key}/block{index // n}").shuffle(perm)
    return perm[index % n]


def stem_key(typ: str, passage_id: str, stem: str, script: str, choices: list[str]) -> tuple:
    """Duplicate-stem key. ★ stems are mostly slots (彼は　＿＿＿…), so their chunks are part of the key."""
    extra = tuple(sorted(choices)) if typ == "sentence_assembly" else ()
    return (typ, passage_id, stem, script, extra)


def place(correct: str, wrong: list[str], key: str, slot: int) -> tuple[list[str], int]:
    others = list(wrong)
    seeded(key + "/order").shuffle(others)
    choices = others[:slot] + [correct] + others[slot:]
    return choices, slot


def gloss(w: Word) -> str:
    return "; ".join(w.glosses[:3])


def passes(lv: int) -> list[int]:
    """Sentence-level floors: strict (all words at the level or easier), then one level harder."""
    return list(dict.fromkeys([lv, max(lv - 1, 1)]))


def gen_kanji_items(p: Packs, level: str, target: int, used: set[int], used_words: set[int], kind: str) -> list[dict]:
    """kind: kanji_reading | orthography. `used` (sentence ids) and `used_words` are shared by the level's
    vocabulary types so one mock never shows the same sentence or word twice."""
    lv = level_num(level)
    items: list[dict] = []
    abbr = "kr" if kind == "kanji_reading" else "or"
    words = sorted(p.words.values(), key=lambda w: (w.rank, w.id))
    for floor, w in ((f, w) for f in passes(lv) for w in words):
        if len(items) >= target:
            break
        if w.id in used_words:
            continue
        if w.level != lv or w.uk or not w.kanji or coarse_pos(w.pos) == "other" or set(w.pos) & BAD_POS:
            continue
        written = w.kanji[0]
        if not has_kanji(written) or not kanji_ok(p, written, lv):
            continue
        for sid in usable_sentences(p, w, floor, used):
            ja, en, _ = p.sentences[sid]
            span = find_span(p.lattice.tokenize(ja), w, ja)
            if not span or not has_kanji(span.surface):
                continue
            parts = split_tail(span.surface, span.reading)
            if not parts:
                continue
            head, core, core_r, tail = parts
            if not written.startswith(head + core):
                continue
            dict_tail = hira(written[len(head) + len(core):])
            dict_reading = hira(head) + core_r + dict_tail
            if dict_reading not in w.readings_for.get(written, []):
                continue
            key = f"{level}/{kind}/{w.id}/{sid}"
            if kind == "kanji_reading":
                wrong = wrong_readings(p, head, core, core_r, tail, written, dict_tail, key)
                correct = span.reading
                stem = ja[:span.start] + U_OPEN + span.surface + U_CLOSE + ja[span.end:]
                expl = (f"{span.surface} is read {span.reading} here ({written} 【{dict_reading}】: {gloss(w)}). "
                        f"JMdict gives no reading {', '.join(wrong)} for {written}. Sentence: “{en}”")
            else:
                wrong = wrong_spellings(p, head, core, core_r, tail, written[len(head) + len(core):],
                                        dict_reading, lv, key)
                correct = span.surface
                stem = ja[:span.start] + U_OPEN + span.reading + U_CLOSE + ja[span.end:]
                expl = (f"{span.reading} is written {span.surface} ({written}: {gloss(w)}). "
                        f"The other choices swap in a kanji with a similar reading or shape; none is a JMdict "
                        f"spelling of {dict_reading}. Sentence: “{en}”")
            if len(wrong) < 3 or len(set(wrong + [correct])) < 4 or not p.claim_stem(kind, stem, []):
                continue
            choices, answer = place(correct, wrong, key, answer_slot(f"{level}/{kind}", len(items)))
            used.add(sid)
            used_words.add(w.id)
            items.append(item(f"jlg-{level.lower()}-{abbr}-{len(items) + 1:04d}", level, kind, stem, choices,
                              answer, expl, [f"v:{w.id}", f"t:{sid}"]))
            break
    return items


# --- context (文脈規定) ---------------------------------------------------------------------------------------

STOP = {"to", "a", "an", "the", "of", "be", "one's", "oneself", "someone", "something", "etc.", "(", ")", "in",
        "on", "at", "for", "with", "and", "or", "as", "by", "up", "out", "from", "into", "about", "is", "it"}


def gloss_words(w: Word) -> set[str]:
    out = set()
    for g in w.glosses:
        for x in re.findall(r"[a-z][a-z'-]+", re.sub(r"\([^)]*\)", "", g.lower())):
            if x not in STOP:
                out.add(x)
    return out


COLLOC_PARTICLES = {"を", "が", "に", "で", "と"}
GENERIC_PREDICATES = {"ある", "いる", "する", "なる", "見る", "言う", "ない", "いい", "よい", "良い", "好き", "嫌い",
                      "欲しい", "思う", "できる", "出来る", "くれる", "もらう", "あげる", "やる", "持つ", "行く",
                      "来る", "使う", "買う", "見せる", "探す", "待つ", "話す", "聞く", "知る", "わかる", "分かる"}
TE_TA = {"た", "だ", "て", "で", "たら", "だら", "たり", "だり", "ても", "でも"}


def inflect_like(p: Packs, span: Span, base: str) -> str | None:
    """Inflect `base` like the span's head token, keeping the trailing auxiliaries (voicing た/て to だ/で after
    godan ガ/ナ/バ/マ-row verbs)."""
    head = span.tokens[0]
    rest = span.tokens[1:]
    if not head.conj_form:
        return base + "".join(t.surface for t in rest)
    forms = p.lattice.forms_of(base)
    if not forms:
        return None
    te_ta = bool(rest) and rest[0].surface in TE_TA
    if te_ta and head.conj_form in {"連用タ接続", "連用形"}:
        prefs = ["連用タ接続", "連用形"]
    else:
        prefs = [head.conj_form]
    for want in prefs:
        # prefer standard forms over the dialectal ウ音便 rows (吸うて) that ipadic also lists
        hits = sorted(("ウ音便" in ct, ct, min(lst)[0]) for (ct, cf), lst in forms.items() if cf == want)
        if hits:
            _, ctype, surface = hits[0]
            break
    else:
        return None
    tail = "".join(t.surface for t in rest)
    if te_ta:
        voiced = ctype.startswith(("五段・ガ行", "五段・ナ行", "五段・バ行", "五段・マ行"))
        first = rest[0].surface
        plain = {"だ": "た", "で": "て", "だら": "たら", "だり": "たり", "でも": "ても"}.get(first, first)
        swap = {"た": "だ", "て": "で", "たら": "だら", "たり": "だり", "ても": "でも"}
        tail = (swap[plain] if voiced else plain) + tail[len(first):]
    return surface + tail


def slot_class(head) -> str | None:
    """Word class of the blanked slot, from the tokenizer (distractors must share it)."""
    if head.pos1 == "動詞" and head.pos2 == "自立":
        return "verb"
    if head.pos1 == "形容詞" and head.pos2 == "自立":
        return "adj-i"
    if head.pos1 == "副詞":
        return "adv"
    if head.pos1 == "名詞":
        if head.pos2 == "形容動詞語幹":
            return "adj-na"
        if head.pos2 in {"一般", "サ変接続"}:
            return "noun"
    return None


def gen_context(p: Packs, level: str, target: int, used: set[int], used_words: set[int]) -> list[dict]:
    lv = level_num(level)
    pool: dict[str, list[Word]] = defaultdict(list)
    for w in sorted(p.words.values(), key=lambda w: (w.rank, w.id)):
        if w.level == lv and not (set(w.pos) & BAD_POS) and coarse_pos(w.pos) != "other":
            pool[coarse_pos(w.pos)].append(w)
    items: list[dict] = []
    order = sorted((w for ws in pool.values() for w in ws), key=lambda w: (w.rank, w.id))
    for floor, w in ((f, w) for f in passes(lv) for w in order):
        if len(items) >= target:
            break
        if w.id in used_words:
            continue
        pos = coarse_pos(w.pos)
        trans = {"vt", "vi"} & set(w.pos)
        mine = gloss_words(w)
        for sid in usable_sentences(p, w, floor, used, max_len=40):
            ja, en, _ = p.sentences[sid]
            if len(ja) < 10:
                continue
            toks = p.lattice.tokenize(ja)
            span = find_span(toks, w, ja)
            if not span or slot_class(span.head) != pos:
                continue
            # neighbours: the nearest content word on the left (+ particles), and the next token on the right
            idx = next(i for i, t in enumerate(toks) if t.start == span.start)
            left, k = "", idx - 1
            while k >= 0 and toks[k].pos1 == "助詞" and len(left) < 3:
                left = toks[k].surface + left
                k -= 1
            has_left_word = k >= 0 and toks[k].pos1 in {"名詞", "動詞", "形容詞", "副詞"}
            if has_left_word:
                left = toks[k].surface + left
            j = next(i for i, t in enumerate(toks) if t.end == span.end) + 1
            right = toks[j].surface if j < len(toks) and toks[j].pos1 != "記号" else ""
            if not has_left_word and not (right and toks[j].pos1 in {"名詞", "動詞", "形容詞"}):
                continue  # too little context to rule the distractors out
            colloc = ""
            if pos in {"noun", "adj-na"}:
                # nouns fit almost any slot (彼は（　　）が好き); only use a noun whose slot is fixed by a
                # collocation: particle + a non-generic predicate, attested at least twice with this noun.
                if not (j + 1 < len(toks) and toks[j].pos1 == "助詞" and toks[j].surface in COLLOC_PARTICLES
                        and toks[j + 1].pos1 in {"動詞", "形容詞"} and toks[j + 1].pos2 == "自立"
                        and toks[j + 1].base not in GENERIC_PREDICATES):
                    continue
                colloc = toks[j].surface + toks[j + 1].base[:-1]
                if p.corpus.count(span.surface + colloc) < 2:
                    continue
            elif not has_left_word:
                continue
            elif pos == "adv":
                # the adverb must collocate with what follows (attested elsewhere in Tatoeba)
                if not right or p.corpus.count(span.surface + right) < 2:
                    continue
            elif p.corpus.count(left + span.head.surface) < 2 or toks[k].pos2 == "代名詞":
                continue  # verbs/adjectives: the left neighbour must be a real collocate (not 彼が（　　）)
            suru = "vs" in w.pos and j < len(toks) and toks[j].base == "する"
            key = f"{level}/context/{w.id}/{sid}"
            cands = [d for d in pool[pos] if d.id != w.id]
            seeded(key).shuffle(cands)
            wrong: list[str] = []
            for d in cands:
                if trans and pos == "verb" and not (trans & set(d.pos)):
                    continue
                if suru and "vs" not in d.pos:
                    continue
                if gloss_words(d) & mine:
                    continue
                base = d.written
                if pos in {"verb", "adj-i"}:
                    surf = inflect_like(p, span, base)
                    stem = base[:-1]
                else:
                    surf = base + "".join(t.surface for t in span.tokens[1:])
                    stem = base
                if not surf or surf == span.surface or surf in wrong or surf in ja or not stem:
                    continue
                if left and p.attested(left, stem):
                    continue
                if right and p.attested(surf, right):
                    continue
                if len(stem) == 1 and left and p.attested(left[-1:], stem):
                    continue
                if colloc and p.attested(stem, colloc):
                    continue
                wrong.append(surf)
                if len(wrong) == 3:
                    break
            if len(wrong) < 3:
                continue
            stem_text = ja[:span.start] + BLANK + ja[span.end:]
            if not p.claim_stem("context", stem_text, []):
                continue
            choices, answer = place(span.surface, wrong, key, answer_slot(f"{level}/context", len(items)))
            used.add(sid)
            used_words.add(w.id)
            expl = (f"“{en}” Only {span.surface} ({w.written}: {gloss(w)}) fits. The others are {level} words of "
                    f"the same part of speech that do not fit this context.")
            items.append(item(f"jlg-{level.lower()}-cx-{len(items) + 1:04d}", level, "context", stem_text, choices,
                              answer, expl, [f"v:{w.id}", f"t:{sid}"]))
            break
    return items


# --- grammar ------------------------------------------------------------------------------------------------


def utf16_to_py(s: str, off: int) -> int:
    n = 0
    for i, c in enumerate(s):
        if n >= off:
            return i
        n += 2 if ord(c) > 0xFFFF else 1
    return len(s)


@dataclass
class GPoint:
    id: str
    level: int
    title: str
    meaning: str
    related: list[str]
    patterns: list[re.Pattern]
    examples: list[tuple[int, str, str, int, int, int | None, str]]  # ord, ja, en, start, end, tatoeba id, source


def load_grammar(p: Packs) -> dict[str, GPoint]:
    if p.grammar is None:
        return {}
    pts: dict[str, GPoint] = {}
    for pid, jlpt, title, meaning, related in p.grammar.execute(
        "SELECT id, jlpt, title, meaning, related FROM grammar_point ORDER BY jlpt DESC, ord"
    ):
        pts[pid] = GPoint(pid, jlpt, title, meaning, json.loads(related or "[]"), [], [])
    for pid, rx in p.grammar.execute("SELECT point_id, regex FROM grammar_pattern ORDER BY point_id, ord"):
        if pid in pts:
            try:
                pts[pid].patterns.append(re.compile(rx))
            except re.error:
                pass
    for pid, o, ja, en, bs, be, src, tid in p.grammar.execute(
        "SELECT point_id, ord, ja, en, blank_start, blank_end, source, tatoeba_id FROM grammar_example "
        "ORDER BY point_id, ord"
    ):
        if pid in pts:
            s, e = utf16_to_py(ja, bs), utf16_to_py(ja, be)
            if 0 <= s < e <= len(ja):
                pts[pid].examples.append((o, ja, en, s, e, tid, src))
    return pts


def meaning_words(m: str) -> set[str]:
    return {x for x in re.findall(r"[a-z][a-z'-]+", re.sub(r"\([^)]*\)", "", m.lower()))} - STOP


FUNCTION_AUX = {"だ", "です", "ます", "た", "ない", "う", "ん", "ぬ"}


def blank_ok(p: Packs, ja: str, s: int, e: int) -> bool:
    """A usable grammar blank: it starts and ends on token boundaries, contains kana and no digits/Latin, and is
    more than a bare particle or a copula/ます/た ending (those have too many acceptable alternatives for a
    rule-built item to be unambiguous: 私（は／も）…, 学生（です／でした）)."""
    text = ja[s:e]
    if not any(is_hira(c) for c in text) or re.search(r"[0-9０-９A-Za-zＡ-Ｚａ-ｚ]", text):
        return False
    toks = p.lattice.tokenize(ja)
    starts = {t.start for t in toks}
    ends = {t.end for t in toks}
    if s not in starts or e not in ends:
        return False
    inner = [t for t in toks if s <= t.start and t.end <= e]
    if not inner or all(t.pos1 in {"助詞", "記号"} for t in inner):
        return False
    if all(t.pos1 in {"助動詞", "記号"} and t.base in FUNCTION_AUX | {"。"} for t in inner):
        return False
    # a grammar form, not a lexical choice (給料を（あげる／もらう）): at least one function word
    if not any(t.pos1 in {"助詞", "助動詞"} or t.pos2 in {"非自立", "接尾"} for t in inner):
        return False
    # must not end mid-word (もらっ｜た, てくれませ｜ん)
    after = [t for t in toks if t.start == e]
    continues = bool(after) and (after[0].pos1 == "助動詞" or (
        after[0].pos1 == "助詞" and after[0].pos2 == "接続助詞" and after[0].surface in {"て", "で", "ば"}))
    return not (continues or inner[-1].surface.endswith("っ")
                or inner[-1].conj_form.startswith(("未然", "連用タ接続")))


def connection(p: Packs, ja: str, s: int) -> str:
    """What the blank attaches to: part of speech (+ conjugated form) of the token before it."""
    prev = [t for t in p.lattice.tokenize(ja) if t.end == s]
    if not prev:
        return "BOS"
    t = prev[0]
    return f"{t.pos1}/{t.conj_form}" if t.conj_form else f"{t.pos1}/{t.pos2}"


def gen_grammar_form(p: Packs, pts: dict[str, GPoint], level: str, target: int, used: set[int]) -> list[dict]:
    """Distractors come from examples of other points whose blank attaches to a different kind of word (after a
    noun vs after a て-form…), so each is wrong by connection, not merely by nuance: rule-built items cannot
    judge nuance, and a distractor that is also grammatical would make the key ambiguous."""
    lv = level_num(level)
    here = [g for g in pts.values() if g.level == lv]
    clean: dict[str, list[tuple[str, str]]] = {}
    for g in pts.values():
        if g.level != lv and not any(g.id in h.related for h in here):
            continue
        opts = set()
        for _, ja, _, s, e, _, _ in g.examples:
            if blank_ok(p, ja, s, e):
                opts.add((ja[s:e], connection(p, ja, s)))
        clean[g.id] = sorted(opts)
    blanks: dict[str, set[str]] = {g.id: {ja[s:e] for _, ja, _, s, e, _, _ in g.examples} for g in pts.values()}
    items: list[dict] = []
    # round-robin over points so every point gets items before any point gets a second one
    rounds = max((len(g.examples) for g in here), default=0)
    for r in range(rounds):
        for g in here:
            if len(items) >= target:
                return items
            exs = [x for x in g.examples if x[6] == "tatoeba" and x[5] not in used]
            if r >= len(exs):
                continue
            _, ja, en, s, e, tid, _ = exs[r]
            ans = ja[s:e]
            if s == 0 or len(ja) > 45 or BLANK in ja or ja.count(ans) != 1 or not blank_ok(p, ja, s, e):
                continue  # (a sentence-initial slot takes almost any adverbial)
            before = connection(p, ja, s)
            mine_conn = {c for _, c in clean.get(g.id, [])} | {before}
            key = f"{level}/grammar_form/{g.id}/{tid}"
            related = [pts[x] for x in g.related if x in pts]
            same = [x for x in here if x.id != g.id and x.id not in g.related]
            seeded(key).shuffle(same)
            mine = meaning_words(g.meaning)
            wrong: list[str] = []
            wrong_pts: list[GPoint] = []
            for other in related + same:
                if meaning_words(other.meaning) & mine:
                    continue
                opts = [o for o, c in clean.get(other.id, []) if c not in mine_conn]
                seeded(key + other.id).shuffle(opts)
                for d in opts:
                    if d == ans or d in blanks[g.id] or d in wrong or ans in d or d in ans:
                        continue
                    if d[:2] == ans[:2] or any(d[:2] == w[:2] for w in wrong):
                        continue  # same head (はずがない / はずだった): likely variants of each other
                    if abs(len(d) - len(ans)) > 4:
                        continue
                    filled = ja[:s] + d + ja[e:]
                    if any(rx.search(filled) for rx in g.patterns):
                        continue
                    if p.attested(ja[max(0, s - 2):s], d, ja[e:e + 1]):
                        continue
                    wrong.append(d)
                    wrong_pts.append(other)
                    break
                if len(wrong) == 3:
                    break
            if len(wrong) < 3 or not p.claim_stem("grammar_form", ja[:s] + BLANK + ja[e:], []):
                continue
            choices, answer = place(ans, wrong, key, answer_slot(f"{level}/grammar_form", len(items)))
            used.add(tid)
            others = "; ".join(f"{d} ({o.title}: {o.meaning})" for d, o in zip(wrong, wrong_pts))
            expl = (f"“{en}” {g.title}: {g.meaning}. The other choices are patterns that attach to a different kind "
                    f"of word, so they cannot follow {ja[max(0, s - 4):s] or 'the start'} here: {others}.")
            items.append(item(f"jlg-{level.lower()}-gf-{len(items) + 1:04d}", level, "grammar_form",
                              ja[:s] + BLANK + ja[e:], choices, answer, expl, [f"g:{g.id}", f"t:{tid}"]))
    return items


INDEPENDENT = {"名詞", "動詞", "形容詞", "副詞", "連体詞", "接続詞", "感動詞", "接頭詞"}
FREE_PARTICLES = {"が", "を", "に", "で", "へ", "と", "から", "まで", "は", "も", "より"}


def bunsetsu(tokens) -> list[list]:
    """Split tokens into bunsetsu: a content word (plus compound nouns, suffixes, prefixes) followed by its
    function words. 名詞・非自立 (こと, の, よう, ため…) starts its own chunk, which suits ★ items."""
    chunks: list[list] = []
    for i, t in enumerate(tokens):
        prev = tokens[i - 1] if i else None
        starts = t.pos1 in INDEPENDENT
        if t.pos1 == "名詞" and t.pos2 in {"接尾"}:
            starts = False
        if t.pos1 == "動詞" and t.pos2 in {"非自立", "接尾"}:
            starts = False
        if t.pos1 == "形容詞" and t.pos2 == "非自立":
            starts = False
        if prev is not None and prev.pos1 == "接頭詞":
            starts = False
        if (t.pos1 == "名詞" and prev is not None and prev.pos1 == "名詞" and t.pos2 != "非自立"
                and prev.pos2 != "非自立"):
            starts = False
        if t.pos1 == "動詞" and t.base == "する" and prev is not None and prev.pos2 == "サ変接続":
            starts = False  # 勉強する stays one chunk
        if t.pos1 == "形容詞" and prev is not None and prev.pos1 == "名詞" and prev.pos2 == "一般":
            starts = False  # 礼儀正しい, 気持ちいい
        if t.pos1 == "記号" and t.surface in "「『（":
            starts = True
        if starts or not chunks:
            chunks.append([t])
        else:
            chunks[-1].append(t)
    return chunks


def is_free_chunk(ch) -> bool:
    """Chunks that can usually be moved around a clause without breaking it: an argument ending in a case/topic
    particle (本を, そこへ, 方へ, nominalized 言いつけで), a bare adverb, or an adverbial noun (昨日, 毎朝).
    A ★ window with two of these often has two correct orders, so it is rejected."""
    if len(ch) == 1 and (ch[0].pos1 == "副詞" or (ch[0].pos1 == "名詞" and ch[0].pos2 == "副詞可能")):
        return True
    last = ch[-1]
    if last.pos1 != "助詞" or last.surface not in FREE_PARTICLES or len(ch) < 2:
        return False
    body = ch[:-1]
    if any(t.pos1 == "助動詞" for t in body):
        return False
    verbs = [t for t in body if t.pos1 in {"動詞", "形容詞"}]
    return not verbs or (len(verbs) == 1 and body[-1] is verbs[0] and verbs[0].conj_form == "連用形")


def gen_assembly(p: Packs, pts: dict[str, GPoint], level: str, target: int, used: set[int]) -> list[dict]:
    lv = level_num(level)
    here = [g for g in pts.values() if g.level == lv]
    items: list[dict] = []
    rounds = max((len(g.examples) for g in here), default=0)
    for r in range(rounds):
        for g in here:
            if len(items) >= target:
                return items
            exs = [x for x in g.examples if x[6] == "tatoeba" and x[5] not in used]
            if r >= len(exs):
                continue
            _, ja, en, s, e, tid, _ = exs[r]
            if not (12 <= len(ja) <= 45):
                continue
            chunks = bunsetsu(p.lattice.tokenize(ja))
            # chunk spans without trailing punctuation (it stays in the stem)
            spans = []
            for c in chunks:
                core = [t for t in c if t.pos1 != "記号"] or c
                spans.append((c[0].start, core[-1].end))
            texts_all = [ja[a0:b0] for a0, b0 in spans]
            best = None
            for a in range(1, len(chunks) - 3):  # a >= 1: some text before the slots
                win = list(range(a, a + 4))
                if any(all(t.pos1 == "記号" for t in chunks[i]) for i in win):
                    continue
                if any(chunks[i][-1].pos1 == "記号" and i != win[-1] for i in win):
                    continue  # punctuation inside the window
                ws, we = spans[a][0], spans[a + 3][1]
                if we <= s or ws >= e:
                    continue  # must include part of the grammar construction
                texts = [texts_all[i] for i in win]
                if len(set(texts)) < 4 or any(len(x) > 12 or not x for x in texts):
                    continue
                if sum(is_free_chunk(chunks[i]) for i in win) > 1:
                    continue
                ends = [chunks[i][-1].surface for i in win if chunks[i][-1].pos1 == "助詞"]
                if len(ends) != len(set(ends)):
                    continue
                best = (a, texts, ws, we)
                break
            if best is None:
                continue
            a, texts, ws, we = best
            key = f"{level}/sentence_assembly/{g.id}/{tid}"
            stem = ja[:ws] + f"\u3000{SLOT}\u3000{SLOT}\u3000{STAR}\u3000{SLOT}"
            rest = ja[we:]
            stem += ("\u3000" + rest if rest and not all(c in "。！？!?" for c in rest) else rest)
            correct = texts[2]
            if not p.claim_stem("sentence_assembly", stem, texts):
                continue
            choices, answer = place(correct, texts[:2] + texts[3:], key,
                                    answer_slot(f"{level}/sentence_assembly", len(items)))
            expl = (f"Correct order: {' / '.join(texts)} → {ja} (“{en}”). ★ is {correct}. "
                    f"Grammar point: {g.title} ({g.meaning}).")
            used.add(tid)
            items.append(item(f"jlg-{level.lower()}-sa-{len(items) + 1:04d}", level, "sentence_assembly", stem,
                              choices, answer, expl, [f"g:{g.id}", f"t:{tid}"]))
    return items


# --- item construction & generate command -------------------------------------------------------------------


def item(iid: str, level: str, typ: str, stem: str, choices: list[str], answer: int, expl: str,
         refs: list[str], source: str = "generated") -> dict:
    return {
        "id": iid, "exam": "JLPT", "level": level, "type": typ, "stem": nfc(stem),
        "choices": [nfc(c) for c in choices], "answer": answer, "explanation": nfc(expl), "refs": refs,
        "source": source, "verified": False,
    }


def generate(packs: Path, out: Path, per_type: int, blueprint: dict[str, dict[str, int]]) -> dict:
    t0 = time.time()
    p = Packs(packs)
    pts = load_grammar(p)
    items: list[dict] = []
    report: dict[str, dict[str, int]] = {}
    for level in LEVELS:
        allowed = blueprint.get(level, {})
        used_vocab: set[int] = set()
        used_words: set[int] = set()
        used_grammar: set[int] = set()
        rep = report.setdefault(level, {})
        for typ in GENERATED_TYPES:
            if typ not in allowed:
                continue
            if typ in {"kanji_reading", "orthography"}:
                got = gen_kanji_items(p, level, per_type, used_vocab, used_words, typ)
            elif typ == "context":
                got = gen_context(p, level, per_type, used_vocab, used_words)
            elif typ == "grammar_form":
                got = gen_grammar_form(p, pts, level, per_type, used_grammar)
            else:
                got = gen_assembly(p, pts, level, per_type, used_grammar)
            rep[typ] = len(got)
            items += got
            print(f"{level} {typ}: {len(got)}", file=sys.stderr, flush=True)
    bank = dict(GENERATED_BANK)
    bank["passages"] = []
    bank["items"] = items
    out.parent.mkdir(parents=True, exist_ok=True)
    write_bank(out, bank)
    print(f"wrote {len(items)} items to {out} ({out.stat().st_size / 1e6:.2f} MB) in {time.time() - t0:.0f}s",
          file=sys.stderr)
    return report


def write_bank(path: Path, bank: dict) -> None:
    """One item/passage per line: stable diffs, reviewable, and compact."""
    lines = ["{"]
    for k in ("bank", "title", "license", "attribution"):
        lines.append(f"  {json.dumps(k)}: {json.dumps(bank[k], ensure_ascii=False)},")
    for k in ("passages", "items"):
        rows = bank.get(k, [])
        lines.append(f"  {json.dumps(k)}: [")
        for i, r in enumerate(rows):
            lines.append("    " + json.dumps(r, ensure_ascii=False) + ("," if i < len(rows) - 1 else ""))
        lines.append("  ]" + ("," if k == "passages" else ""))
    lines.append("}")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")


# --- validation ---------------------------------------------------------------------------------------------


@dataclass
class Report:
    errors: list[str] = field(default_factory=list)
    warnings: list[str] = field(default_factory=list)
    counts: Counter = field(default_factory=Counter)  # (level, type) -> items
    vocab_warnings: Counter = field(default_factory=Counter)  # (level, type) -> items with above-level words


def _strings(obj):
    if isinstance(obj, str):
        yield obj
    elif isinstance(obj, dict):
        for v in obj.values():
            yield from _strings(v)
    elif isinstance(obj, list):
        for v in obj:
            yield from _strings(v)


def load_form_level(dictionary: Path) -> dict[str, int]:
    """Written form (containing kanji) -> easiest JLPT level of any JMdict entry spelled that way."""
    con = sqlite3.connect(f"file:{dictionary}?mode=ro", uri=True)
    fl: dict[str, int] = {}
    for text, jlpt in con.execute(
        "SELECT k.text, e.jlpt FROM entry_kanji k JOIN entry e ON e.id = k.entry_id WHERE e.jlpt IS NOT NULL"
    ):
        if has_kanji(text):
            fl[text] = max(fl.get(text, 0), jlpt)
    con.close()
    return fl


def above_level_words(text: str, level: int, form_level: dict[str, int], lattice=None) -> list[str]:
    """Kanji-containing words whose easiest JLPT level is above `level`. With the tokenizer pack, the dictionary
    (base) form of each content word is checked, so inflected verbs match (会っ → 会う); without it, a simple
    longest match over the text."""
    text = strip_markup(text)
    if lattice is not None:
        out = []
        for t in lattice.tokenize(text):
            # suffixes (室, 的), pronouns (彼) and lone kanji (時, 日) are too ambiguous to flag usefully
            if (t.pos1 not in {"名詞", "動詞", "形容詞", "副詞"} or len(t.base) < 2
                    or t.pos2 in {"固有名詞", "数", "接尾", "代名詞", "非自立"}):
                continue
            lv = form_level.get(t.base)
            if lv is not None and lv < level and has_kanji(t.base):
                out.append(f"{t.base}(N{lv})")
        return out
    out = []
    i = 0
    while i < len(text):
        hit = None
        for n in range(min(8, len(text) - i), 0, -1):
            sub = text[i:i + n]
            if has_kanji(sub) and sub in form_level:
                hit = sub
                break
        if hit:
            if form_level[hit] < level:
                out.append(f"{hit}(N{form_level[hit]})")
            i += len(hit)
        else:
            i += 1
    return out


def validate_banks(banks: list[tuple[str, dict]], blueprint: dict[str, dict[str, int]],
                   form_level: dict[str, int] | None = None, lattice=None) -> Report:
    rep = Report()
    passage_ids: dict[str, dict] = {}
    item_ids: set[str] = set()
    stems: dict[tuple, str] = {}
    for name, bank in banks:
        err = rep.errors.append
        for k in ("bank", "title", "license", "attribution"):
            if not isinstance(bank.get(k), str) or not bank.get(k):
                err(f"{name}: missing or empty '{k}'")
        if not isinstance(bank.get("items"), list):
            err(f"{name}: 'items' must be a list")
            continue
        if not isinstance(bank.get("passages", []), list):
            err(f"{name}: 'passages' must be a list")
            continue
        for s in _strings(bank):
            if not unicodedata.is_normalized("NFC", s):
                err(f"{name}: text not NFC: {s[:30]!r}")
        for ps in bank.get("passages", []):
            pid = ps.get("id")
            where = f"{name}: passage {pid}"
            if not isinstance(pid, str) or not pid:
                err(f"{name}: passage without id")
                continue
            if pid in passage_ids:
                err(f"{where}: duplicate passage id")
            passage_ids[pid] = ps
            _check_common(ps, where, err, blueprint, passage=True)
            if not isinstance(ps.get("body"), str):
                err(f"{where}: body must be a string")
            if "script" in ps:
                _check_script(ps["script"], where, err)
            if not (ps.get("body") or ps.get("script")):
                err(f"{where}: needs a body or a script")
            for k in ("textType", "title"):
                if not isinstance(ps.get(k), str) or not ps.get(k):
                    err(f"{where}: missing '{k}'")
            _check_markup(ps.get("body", ""), where, err)
        for it in bank["items"]:
            iid = it.get("id")
            where = f"{name}: item {iid}"
            if not isinstance(iid, str) or not iid:
                err(f"{name}: item without id")
                continue
            if iid in item_ids:
                err(f"{where}: duplicate item id")
            item_ids.add(iid)
            _check_common(it, where, err, blueprint, passage=False)
            typ, level = it.get("type"), it.get("level")
            stem, choices, answer = it.get("stem"), it.get("choices"), it.get("answer")
            if not isinstance(stem, str) or (not stem and not it.get("script")):
                err(f"{where}: stem must be a non-empty string")
                stem = ""
            want = 3 if typ in THREE_CHOICE_TYPES else 4
            if not isinstance(choices, list) or not all(isinstance(c, str) and c.strip() for c in choices):
                err(f"{where}: choices must be non-empty strings")
                choices = []
            elif it.get("exam") == "JLPT" and len(choices) != want:
                err(f"{where}: {typ} needs {want} choices, has {len(choices)}")
            elif it.get("exam") != "JLPT" and len(choices) != 4:
                err(f"{where}: needs 4 choices")
            if len(set(choices)) != len(choices):
                err(f"{where}: choices not distinct")
            if not isinstance(answer, int) or isinstance(answer, bool) or not (0 <= answer < max(len(choices), 1)):
                err(f"{where}: answer {answer!r} out of range")
            if not isinstance(it.get("explanation"), str) or not it.get("explanation", "").strip():
                err(f"{where}: missing explanation")
            refs = it.get("refs", [])
            if not isinstance(refs, list) or not all(isinstance(r, str) and re.match(r"^[a-z]+:.+", r) for r in refs):
                err(f"{where}: refs must be strings like 'g:<id>' / 'v:<id>'")
            if "script" in it:
                _check_script(it["script"], where, err)
            _check_markup(stem, where, err)
            pid = it.get("passageId")
            if pid is not None and not isinstance(pid, str):
                err(f"{where}: passageId must be a string")
            script_text = "|".join(x.get("text", "") for x in it.get("script", []) if isinstance(x, dict))
            key = stem_key(typ, pid or "", stem, script_text, choices)
            if key in stems:
                err(f"{where}: duplicate stem (same as {stems[key]})")
            stems[key] = iid
            if it.get("exam") == "JLPT" and level in blueprint:
                rep.counts[(level, typ)] += 1
                if typ == "sentence_assembly" and (stem.count(STAR) != 1 or stem.count(SLOT) != 3):
                    err(f"{where}: sentence_assembly stem needs 3 {SLOT} slots and one {STAR}")
                if typ in {"kanji_reading", "orthography", "paraphrase"} and stem.count(U_OPEN) != 1:
                    err(f"{where}: {typ} stem needs exactly one <u>…</u>")
                if typ in {"context", "grammar_form", "word_formation"} and BLANK not in stem:
                    err(f"{where}: {typ} stem needs the blank {BLANK}")
                if form_level is not None:
                    # kanji_reading/orthography distractors are non-words by design: check the stem only
                    texts = [stem] if typ in {"kanji_reading", "orthography"} else [stem, *choices]
                    if typ == "quick_response":  # the stem is the fixed instruction; the prompt is the script
                        texts = [x.get("text", "") for x in it.get("script", []) if isinstance(x, dict)] + choices
                    hard = sorted({w for t in texts for w in above_level_words(t, level_num(level), form_level, lattice)})
                    if hard:
                        rep.vocab_warnings[(level, typ)] += 1
                        rep.warnings.append(f"{where}: above-level words {', '.join(hard[:5])}")
    # cross-file passage checks
    for name, bank in banks:
        for it in bank.get("items", []):
            pid = it.get("passageId")
            if pid is None:
                continue
            ps = passage_ids.get(pid)
            where = f"{name}: item {it.get('id')}"
            if ps is None:
                rep.errors.append(f"{where}: passageId {pid} not found")
                continue
            if ps.get("level") != it.get("level") or ps.get("exam") != it.get("exam"):
                rep.errors.append(f"{where}: level/exam differs from passage {pid}")
            if it.get("type") == "text_grammar":
                m = TG_MARK.fullmatch(it.get("stem", ""))
                if not m or it["stem"] not in ps.get("body", ""):
                    rep.errors.append(f"{where}: text_grammar stem must be a ［n］ marker present in the passage")
            if form_level is not None and it.get("exam") == "JLPT" and it.get("level") in blueprint:
                body = ps.get("body", "") + "".join(x.get("text", "") for x in ps.get("script", []))
                hard = sorted(set(above_level_words(body, level_num(it["level"]), form_level, lattice)))
                if hard and not ps.get("_warned"):
                    ps["_warned"] = True
                    rep.warnings.append(f"{name}: passage {pid}: above-level words {', '.join(hard[:6])}")
    for ps in passage_ids.values():
        ps.pop("_warned", None)
    used = {it.get("passageId") for _, b in banks for it in b.get("items", [])}
    for pid in passage_ids:
        if pid not in used:
            rep.warnings.append(f"passage {pid} has no items")
    return rep


def _check_common(obj: dict, where: str, err, blueprint: dict[str, dict[str, int]], passage: bool) -> None:
    exam, level = obj.get("exam"), obj.get("level")
    if exam not in EXAMS:
        err(f"{where}: exam must be one of {sorted(EXAMS)}")
    if exam == "JLPT":
        if level not in LEVELS:
            err(f"{where}: JLPT level must be N5..N1, got {level!r}")
        elif not passage and obj.get("type") not in blueprint.get(level, {}):
            err(f"{where}: type {obj.get('type')!r} is not in the {level} blueprint")
    elif not isinstance(level, str) or not level:
        err(f"{where}: missing level")
    if not isinstance(obj.get("source"), str) or not obj.get("source"):
        err(f"{where}: missing source")
    if not isinstance(obj.get("verified"), bool):
        err(f"{where}: verified must be true/false")
    if obj.get("source") == "llm" and obj.get("verified") is not False:
        err(f"{where}: source=llm items must stay verified=false until review")


def _check_script(script, where: str, err) -> None:
    if not isinstance(script, list) or not script:
        err(f"{where}: script must be a non-empty list")
        return
    for line in script:
        if not isinstance(line, dict) or not isinstance(line.get("text"), str) or not line.get("text"):
            err(f"{where}: script lines need text")
        elif line.get("voice") not in VOICES or not isinstance(line.get("speaker"), str):
            err(f"{where}: script line needs speaker and voice in {sorted(VOICES)}")


def _check_markup(text: str, where: str, err) -> None:
    if text.count(U_OPEN) != text.count(U_CLOSE) or re.search(r"<u>[^<]*<u>", text):
        err(f"{where}: unbalanced <u>…</u>")
    if re.search(r"<(?!/?u>)[a-zA-Z/][^>]*>", text):
        err(f"{where}: only <u> markup is allowed")


def coverage_table(rep: Report, blueprint: dict[str, dict[str, int]]) -> tuple[str, list[str]]:
    types = []
    for lv in LEVELS:
        for t in blueprint.get(lv, {}):
            if t not in types:
                types.append(t)
    titles = type_titles() if BLUEPRINTS.exists() else {}
    lines = [f"{'type':<22}" + "".join(f"{lv:>12}" for lv in LEVELS)]
    short: list[str] = []
    for t in types:
        row = f"{t:<22}"
        for lv in LEVELS:
            need = blueprint.get(lv, {}).get(t)
            if need is None:
                row += f"{'-':>12}"
                continue
            have = rep.counts[(lv, t)]
            mark = "" if have >= need else " !"
            row += f"{f'{have}/{need}{mark}':>12}"
            if have < need:
                short.append(f"{lv} {t} ({titles.get(t, t)}): {have}/{need}")
        lines.append(row)
    return "\n".join(lines), short


def load_banks(paths: list[Path]) -> list[tuple[str, dict]]:
    return [(p.name, json.loads(p.read_text(encoding="utf-8"))) for p in paths]


# --- draft (any OpenAI-compatible endpoint) -----------------------------------------------------------------

TYPE_GUIDE = {
    "paraphrase": "stem: a sentence with one word/phrase wrapped in <u>…</u>; 4 choices are words/phrases that could "
                  "replace it; exactly one is closest in meaning.",
    "usage": "stem: just the target word; 4 choices are full sentences using it; exactly one uses it correctly, the "
             "others are natural sentences for a different word.",
    "word_formation": "stem: a sentence with （　　） where a prefix/suffix/compound element goes; 4 choices "
                      "are such elements (未, 非, 〜的, 〜化…).",
    "kanji_reading": "stem: a sentence with the target written in kanji inside <u>…</u>; 4 choices are readings in "
                     "hiragana, exactly one correct.",
    "orthography": "stem: a sentence with the target in hiragana inside <u>…</u>; 4 choices are written forms, "
                   "exactly one correct.",
    "context": "stem: a sentence with （　　） for one word; 4 choices are same-level words of the same part "
               "of speech; exactly one fits.",
    "grammar_form": "stem: a sentence with （　　） for a grammar form; 4 choices are grammar forms; exactly "
                    "one fits.",
    "utterance": "stem: a situation described in Japanese ending in 何と言いますか。; 3 choices are utterances; "
                 "exactly one is appropriate.",
    "quick_response": "stem: exactly 最もよい返事を選んでください。; include \"script\": [{\"speaker\": \"女\", "
                      "\"voice\": \"female\", \"text\": \"<one-line prompt>\"}]; 3 reply choices; exactly one natural.",
}


def draft(endpoint: str, model: str, level: str, typ: str, count: int, api_key: str | None,
          blueprint: dict[str, dict[str, int]], timeout: int = 600) -> dict:
    if level not in blueprint or typ not in blueprint[level]:
        raise SystemExit(f"{typ} is not in the {level} blueprint")
    if typ not in TYPE_GUIDE:
        raise SystemExit(f"draft supports {sorted(TYPE_GUIDE)}; passage-based types are authored by hand for now")
    n = 3 if typ in THREE_CHOICE_TYPES else 4
    system = (
        "You write ORIGINAL Japanese-language test items in the style of the JLPT. Never copy or paraphrase official "
        "JLPT items or prep books. Japanese must be natural, NFC, and at or below the requested level. Exactly one "
        "answer is correct and unambiguous. Explanations are in English. Reply with JSON only."
    )
    user = (
        f"Write {count} items. Level: {level}. Type: {typ}. {TYPE_GUIDE[typ]}\n"
        f"Each item has {n} distinct choices. Spread the correct answer position evenly.\n"
        'Reply as {"items": [{"stem": "...", "choices": [...], "answer": <0-based index>, '
        '"explanation": "<English>"' + (', "script": [...]' if typ == "quick_response" else "") + "}]}"
    )
    url = endpoint.rstrip("/")
    if not url.endswith("/chat/completions"):
        url += "/chat/completions" if url.endswith("/v1") else "/v1/chat/completions"
    body = json.dumps({
        "model": model, "temperature": 0.7, "response_format": {"type": "json_object"},
        "messages": [{"role": "system", "content": system}, {"role": "user", "content": user}],
    }).encode()
    headers = {"Content-Type": "application/json"}
    if api_key:
        headers["Authorization"] = f"Bearer {api_key}"
    req = urllib.request.Request(url, data=body, headers=headers)
    with urllib.request.urlopen(req, timeout=timeout) as resp:
        content = json.load(resp)["choices"][0]["message"]["content"]
    return normalize_draft(json.loads(content), level, typ, stamp=time.strftime("%Y%m%d%H%M%S"))


def normalize_draft(data: dict, level: str, typ: str, stamp: str) -> dict:
    """Turn a model's {"items": [...]} into a bank, labeled source=llm / verified=false."""
    items = []
    for i, raw in enumerate(data.get("items", []), 1):
        it = {
            "id": f"jld-{level.lower()}-{typ}-{stamp}-{i:02d}", "exam": "JLPT", "level": level, "type": typ,
            "stem": nfc(str(raw.get("stem", ""))), "choices": [nfc(str(c)) for c in raw.get("choices", [])],
            "answer": raw.get("answer"), "explanation": nfc(str(raw.get("explanation", ""))),
            "refs": [], "source": "llm", "verified": False,
        }
        if raw.get("script"):
            it["script"] = [
                {"speaker": nfc(str(x.get("speaker", "A"))), "voice": x.get("voice", "female"),
                 "text": nfc(str(x.get("text", "")))} for x in raw["script"] if isinstance(x, dict)
            ]
        items.append(it)
    return {
        "bank": f"jlpt-draft-{level.lower()}-{typ}-{stamp}", "title": f"JLPT {level} {typ} drafts",
        "license": "CC BY-SA 4.0", "attribution": "Tsumugi contributors (LLM-drafted, unreviewed)",
        "passages": [], "items": items,
    }


# --- CLI ----------------------------------------------------------------------------------------------------


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    sub = ap.add_subparsers(dest="cmd", required=True)
    g = sub.add_parser("generate", help="rule-based items from the built content packs")
    g.add_argument("--packs", type=Path, default=DEFAULT_PACKS)
    g.add_argument("--out", type=Path, default=HERE / "bank" / "jlpt_generated.json")
    g.add_argument("--per-type", type=int, default=80, help="items per type per level (default 80)")
    v = sub.add_parser("validate", help="check bank files and print the coverage table")
    v.add_argument("files", nargs="+", type=Path)
    v.add_argument("--packs", type=Path, default=DEFAULT_PACKS, help="for the vocabulary-within-level check")
    v.add_argument("--show-warnings", type=int, default=20, help="how many warnings to print (default 20)")
    v.add_argument("--strict-coverage", action="store_true", help="fail when a level lacks a full mock")
    d = sub.add_parser("draft", help="draft items through an OpenAI-compatible endpoint (source=llm)")
    d.add_argument("--endpoint", required=True, help="e.g. http://localhost:11434/v1 (Ollama)")
    d.add_argument("--model", required=True)
    d.add_argument("--level", required=True, choices=LEVELS)
    d.add_argument("--type", required=True, dest="typ")
    d.add_argument("--count", type=int, default=10)
    d.add_argument("--api-key-env", default="TSUMUGI_LLM_API_KEY", help="env var holding an optional API key")
    d.add_argument("--out", type=Path, required=True)
    args = ap.parse_args(argv)
    blueprint = load_blueprint()

    if args.cmd == "generate":
        report = generate(args.packs, args.out, args.per_type, blueprint)
        for level, types in report.items():
            for t, n in types.items():
                if n < 60:
                    print(f"note: {level} {t} reached {n} (< 60)", file=sys.stderr)
        return 0

    if args.cmd == "validate":
        form_level = None
        dict_pack = args.packs / "dictionary.sqlite"
        if dict_pack.exists():
            form_level = load_form_level(dict_pack)
        else:
            print(f"(no {dict_pack}: skipping the vocabulary-within-level check)")
        lattice = None
        if form_level is not None and (args.packs / "tokenizer.sqlite").exists():
            from lattice import Lattice

            lattice = Lattice(args.packs / "tokenizer.sqlite")
        rep = validate_banks(load_banks(args.files), blueprint, form_level, lattice)
        table, short = coverage_table(rep, blueprint)
        print("Coverage (items / needed for one full mock):")
        print(table)
        if short:
            print(f"\n{len(short)} level×type cells short of one full mock:")
            for s in short:
                print(f"  {s}")
        if form_level is not None:
            total = sum(rep.counts.values())
            flagged = sum(rep.vocab_warnings.values())
            how = "dictionary forms via the tokenizer" if lattice else "longest match"
            print(f"\nVocabulary above level: {flagged}/{total} items flagged ({how}, JMdict JLPT tags)")
        for w in rep.warnings[:args.show_warnings]:
            print(f"  warning: {w}")
        if len(rep.warnings) > args.show_warnings:
            print(f"  … {len(rep.warnings) - args.show_warnings} more warnings")
        for e in rep.errors:
            print(f"ERROR: {e}")
        print(f"\n{sum(rep.counts.values())} JLPT items, {len(rep.errors)} errors, {len(rep.warnings)} warnings")
        if rep.errors or (args.strict_coverage and short):
            return 1
        return 0

    if args.cmd == "draft":
        import os

        bank = draft(args.endpoint, args.model, args.level, args.typ, args.count, os.environ.get(args.api_key_env),
                     blueprint)
        rep = validate_banks([("draft", bank)], blueprint)
        for e in rep.errors:
            print(f"ERROR: {e}", file=sys.stderr)
        args.out.parent.mkdir(parents=True, exist_ok=True)
        write_bank(args.out, bank)
        print(f"wrote {len(bank['items'])} drafted items to {args.out} ({len(rep.errors)} validation errors; "
              f"fix them, then review with items/review.py)")
        return 0
    return 2


if __name__ == "__main__":
    sys.exit(main())
