package app.tsumugi.kana

// Generated by tools/items/review.py --ingest (kind "kana_mnemonic"). Do not edit by hand.
// Kana whose mnemonic a human reviewed: their source is "verified" and the AI badge is off (rule 10, D-117).
internal val REVIEWED_KANA_MNEMONICS: Set<String> = setOf(
)
